-- docs/09 TM-14: the application role must never be able to TRUNCATE append-only tables.
CREATE ROLE app WITH LOGIN PASSWORD 'app';
GRANT CONNECT ON DATABASE codekraft TO app;
\c codekraft
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
GRANT USAGE ON SCHEMA public TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app;
