services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: codekraft
      POSTGRES_PASSWORD: codekraft
      POSTGRES_DB: codekraft
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codekraft -d codekraft"]
      interval: 5s
      timeout: 3s
      retries: 10
  minio:
    image: minio/minio
    profiles: ["storage"]
    command: server /data --console-address ":9001"
    environment: { MINIO_ROOT_USER: minio, MINIO_ROOT_PASSWORD: minio12345 }
    ports: ["9000:9000", "9001:9001"]
    volumes: ["minio:/data"]
  minio-mc:
    image: minio/mc
    profiles: ["storage"]
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "sleep 3; mc alias set local http://minio:9000 minio minio12345;
      for b in codekraft-dev-public codekraft-dev-private codekraft-dev-documents codekraft-dev-backups; do mc mb -p local/$$b; done;
      mc anonymous set download local/codekraft-dev-public; exit 0"
  mailpit:
    image: axllent/mailpit
    profiles: ["mail"]
    ports: ["8025:8025", "1025:1025"]
volumes:
  pgdata: {}
  minio: {}
