packages:
  - "."
minimumReleaseAgeExclude:
  - "@better-auth/core@1.7.6"
  - "@better-auth/drizzle-adapter@1.7.6"
  - "@better-auth/kysely-adapter@1.7.6"
  - "@better-auth/memory-adapter@1.7.6"
  - "@better-auth/mongo-adapter@1.7.6"
  - "@better-auth/prisma-adapter@1.7.6"
  - "@better-auth/telemetry@1.7.6"
  - better-auth@1.7.6
allowBuilds:
  "@embedded-postgres/darwin-arm64": true
  "@embedded-postgres/darwin-x64": true
  "@embedded-postgres/linux-arm64": true
  "@embedded-postgres/linux-x64": true
  "@tailwindcss/oxide": true
  argon2: true
  cpu-features: true
  embedded-postgres: true
  esbuild: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
