/**
 * Screen preview registry (dev only). Each entry maps a designed screen (ui/screens/**) to its
 * preview route under /dev/screens. Agents append entries for the screens they build.
 */
export interface ScreenEntry {
  id: string; // SCR-SITE-01 …
  title: string;
  href: string; // /dev/screens/site/landing
  group: "site" | "auth" | "account" | "admin";
  spec: string; // ui/screens/... path
}

export const SCREENS: ScreenEntry[] = [
  // --- site (agent A appends)
  {
    id: "SCR-SITE-01",
    title: "Landing (story chapters)",
    href: "/dev/screens/site/landing",
    group: "site",
    spec: "ui/screens/user/SCR-SITE-01-landing.md",
  },
  {
    id: "SCR-SITE-02",
    title: "Services",
    href: "/dev/screens/site/services",
    group: "site",
    spec: "ui/screens/user/SCR-SITE-02-services.md",
  },
  {
    id: "SCR-SITE-03",
    title: "Products list",
    href: "/dev/screens/site/products",
    group: "site",
    spec: "ui/screens/user/SCR-SITE-03-products-list.md",
  },
  {
    id: "SCR-SITE-04",
    title: "Product detail",
    href: "/dev/screens/site/product-detail",
    group: "site",
    spec: "ui/screens/user/SCR-SITE-04-product-detail.md",
  },
  {
    id: "SCR-SITE-05",
    title: "Case studies list",
    href: "/dev/screens/site/case-studies",
    group: "site",
    spec: "ui/screens/user/SCR-SITE-05-case-studies-list.md",
  },
  {
    id: "SCR-SITE-06",
    title: "Case study detail",
    href: "/dev/screens/site/case-study-detail",
    group: "site",
    spec: "ui/screens/user/SCR-SITE-06-case-study-detail.md",
  },
  {
    id: "SCR-SITE-07",
    title: "Blog index",
    href: "/dev/screens/site/blog",
    group: "site",
    spec: "ui/screens/user/SCR-SITE-07-blog-index.md",
  },
  {
    id: "SCR-SITE-08",
    title: "Blog post",
    href: "/dev/screens/site/blog-post",
    group: "site",
    spec: "ui/screens/user/SCR-SITE-08-blog-post.md",
  },
  {
    id: "SCR-SITE-09",
    title: "Contact / inquiry",
    href: "/dev/screens/site/contact",
    group: "site",
    spec: "ui/screens/user/SCR-SITE-09-contact.md",
  },
  {
    id: "SCR-SITE-10",
    title: "Legal page",
    href: "/dev/screens/site/legal",
    group: "site",
    spec: "ui/screens/user/SCR-SITE-10-legal-page.md",
  },
  {
    id: "SCR-SITE-11",
    title: "System pages (404, error, offline)",
    href: "/dev/screens/site/system?state=not_found",
    group: "site",
    spec: "ui/screens/user/SCR-SITE-11-system-pages.md",
  },
  // --- auth + account + checkout (agent B appends)
  {
    id: "SCR-AUTH-01",
    title: "Login (+ admin TOTP variant)",
    href: "/dev/screens/account/login",
    group: "auth",
    spec: "ui/screens/user/SCR-AUTH-01-login.md",
  },
  {
    id: "SCR-AUTH-02",
    title: "Register",
    href: "/dev/screens/account/register",
    group: "auth",
    spec: "ui/screens/user/SCR-AUTH-02-register.md",
  },
  {
    id: "SCR-AUTH-03",
    title: "Verify email",
    href: "/dev/screens/account/verify-email",
    group: "auth",
    spec: "ui/screens/user/SCR-AUTH-03-verify-email.md",
  },
  {
    id: "SCR-AUTH-04",
    title: "Reset password",
    href: "/dev/screens/account/reset-password",
    group: "auth",
    spec: "ui/screens/user/SCR-AUTH-04-reset-password.md",
  },
  {
    id: "SCR-AUTH-05",
    title: "Phone OTP (flagged)",
    href: "/dev/screens/account/phone-otp",
    group: "auth",
    spec: "ui/screens/user/SCR-AUTH-05-phone-otp.md",
  },
  {
    id: "SCR-ACC-01",
    title: "Account overview",
    href: "/dev/screens/account/overview",
    group: "account",
    spec: "ui/screens/user/SCR-ACC-01-overview.md",
  },
  {
    id: "SCR-ACC-02",
    title: "Purchases & access",
    href: "/dev/screens/account/purchases",
    group: "account",
    spec: "ui/screens/user/SCR-ACC-02-purchases.md",
  },
  {
    id: "SCR-ACC-03",
    title: "Entitlement detail",
    href: "/dev/screens/account/entitlement",
    group: "account",
    spec: "ui/screens/user/SCR-ACC-03-entitlement-detail.md",
  },
  {
    id: "SCR-ACC-04",
    title: "Invoices & payments",
    href: "/dev/screens/account/invoices",
    group: "account",
    spec: "ui/screens/user/SCR-ACC-04-invoices-payments.md",
  },
  {
    id: "SCR-ACC-05",
    title: "Queries (list)",
    href: "/dev/screens/account/queries",
    group: "account",
    spec: "ui/screens/user/SCR-ACC-05-queries.md",
  },
  {
    id: "SCR-ACC-05/thread",
    title: "Query thread",
    href: "/dev/screens/account/query-thread",
    group: "account",
    spec: "ui/screens/user/SCR-ACC-05-queries.md",
  },
  {
    id: "SCR-ACC-06",
    title: "Chatbot",
    href: "/dev/screens/account/chat",
    group: "account",
    spec: "ui/screens/user/SCR-ACC-06-chatbot.md",
  },
  {
    id: "SCR-ACC-07",
    title: "Wishlist",
    href: "/dev/screens/account/wishlist",
    group: "account",
    spec: "ui/screens/user/SCR-ACC-07-wishlist.md",
  },
  {
    id: "SCR-ACC-08",
    title: "Notifications",
    href: "/dev/screens/account/notifications",
    group: "account",
    spec: "ui/screens/user/SCR-ACC-08-notifications.md",
  },
  {
    id: "SCR-ACC-09",
    title: "Profile & settings",
    href: "/dev/screens/account/settings",
    group: "account",
    spec: "ui/screens/user/SCR-ACC-09-profile-settings.md",
  },
  {
    id: "SCR-ACC-10",
    title: "Checkout",
    href: "/dev/screens/account/checkout",
    group: "account",
    spec: "ui/screens/user/SCR-ACC-10-checkout.md",
  },
  {
    id: "SCR-ACC-11",
    title: "Order status",
    href: "/dev/screens/account/order-status",
    group: "account",
    spec: "ui/screens/user/SCR-ACC-11-order-status.md",
  },
  {
    id: "SCR-ACC-12",
    title: "Custom quote",
    href: "/dev/screens/account/quote",
    group: "account",
    spec: "ui/screens/user/SCR-ACC-12-custom-quote.md",
  },
  // --- admin (agent C appends)
  {
    id: "SCR-ADM-01",
    title: "Admin login + TOTP",
    href: "/dev/screens/admin/login",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-01-login-totp.md",
  },
  {
    id: "SCR-ADM-02",
    title: "Widget dashboard + widget library",
    href: "/dev/screens/admin/dashboard",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-02-dashboard.md",
  },
  {
    id: "SCR-ADM-03",
    title: "Products list (+ categories & tags)",
    href: "/dev/screens/admin/products",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-03-products-list.md",
  },
  {
    id: "SCR-ADM-04",
    title: "Product editor (12 tabs)",
    href: "/dev/screens/admin/product-editor",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-04-product-editor.md",
  },
  {
    id: "SCR-ADM-05",
    title: "Approvals inbox",
    href: "/dev/screens/admin/approvals",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-05-approvals-inbox.md",
  },
  {
    id: "SCR-ADM-06",
    title: "Orders list",
    href: "/dev/screens/admin/orders",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-06-orders-list.md",
  },
  {
    id: "SCR-ADM-07",
    title: "Order detail · awaiting confirmation",
    href: "/dev/screens/admin/orders/detail",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-07-order-detail.md",
  },
  {
    id: "SCR-ADM-07 (paid)",
    title: "Order detail · paid + fulfilment",
    href: "/dev/screens/admin/orders/detail-paid",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-07-order-detail.md",
  },
  {
    id: "SCR-ADM-08",
    title: "Manual / project order",
    href: "/dev/screens/admin/manual-order",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-08-manual-order.md",
  },
  {
    id: "SCR-ADM-09",
    title: "Custom quotes",
    href: "/dev/screens/admin/quotes",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-09-custom-quotes.md",
  },
  {
    id: "SCR-ADM-10",
    title: "Customers list",
    href: "/dev/screens/admin/customers",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-10-customers-list.md",
  },
  {
    id: "SCR-ADM-11",
    title: "Customer detail",
    href: "/dev/screens/admin/customers/detail",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-11-customer-detail.md",
  },
  {
    id: "SCR-ADM-12",
    title: "Entitlements & delivery tasks",
    href: "/dev/screens/admin/entitlements",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-12-entitlements-delivery-tasks.md",
  },
  {
    id: "SCR-ADM-13",
    title: "Leads list + pipeline board",
    href: "/dev/screens/admin/leads",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-13-leads-list-pipeline.md",
  },
  {
    id: "SCR-ADM-14",
    title: "Lead detail",
    href: "/dev/screens/admin/leads/detail",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-14-lead-detail.md",
  },
  {
    id: "SCR-ADM-15",
    title: "Queries inbox + thread",
    href: "/dev/screens/admin/queries",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-15-queries-inbox-thread.md",
  },
  {
    id: "SCR-ADM-16",
    title: "Chatbot monitor",
    href: "/dev/screens/admin/chatbot",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-16-chatbot-monitor.md",
  },
  {
    id: "SCR-ADM-17",
    title: "Finance: ledger",
    href: "/dev/screens/admin/finance-ledger",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-17-finance-ledger.md",
  },
  {
    id: "SCR-ADM-18",
    title: "Finance: allocations",
    href: "/dev/screens/admin/finance-allocations",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-18-finance-allocations.md",
  },
  {
    id: "SCR-ADM-19",
    title: "Finance: partners & payouts",
    href: "/dev/screens/admin/finance-partners",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-19-finance-partners-payouts.md",
  },
  {
    id: "SCR-ADM-20",
    title: "Finance: expenses",
    href: "/dev/screens/admin/finance-expenses",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-20-finance-expenses.md",
  },
  {
    id: "SCR-ADM-21",
    title: "Finance: adjustments",
    href: "/dev/screens/admin/finance-adjustments",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-21-finance-adjustments.md",
  },
  {
    id: "SCR-ADM-22",
    title: "Finance: reports & statements",
    href: "/dev/screens/admin/finance-reports",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-22-finance-reports-statements.md",
  },
  {
    id: "SCR-ADM-23",
    title: "Content: landing chapters",
    href: "/dev/screens/admin/content-landing",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-23-content-landing.md",
  },
  {
    id: "SCR-ADM-24",
    title: "Content: services",
    href: "/dev/screens/admin/content-services",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-24-content-services.md",
  },
  {
    id: "SCR-ADM-25",
    title: "Content: case studies",
    href: "/dev/screens/admin/content-case-studies",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-25-content-case-studies.md",
  },
  {
    id: "SCR-ADM-26",
    title: "Content: testimonials & logos",
    href: "/dev/screens/admin/content-testimonials",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-26-content-testimonials-logos.md",
  },
  {
    id: "SCR-ADM-27",
    title: "Content: FAQs",
    href: "/dev/screens/admin/content-faqs",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-27-content-faqs.md",
  },
  {
    id: "SCR-ADM-28",
    title: "Content: legal pages",
    href: "/dev/screens/admin/content-legal",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-28-content-legal.md",
  },
  {
    id: "SCR-ADM-29",
    title: "Settings (9 sections)",
    href: "/dev/screens/admin/settings",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-29-settings.md",
  },
  {
    id: "SCR-ADM-30",
    title: "Audit log",
    href: "/dev/screens/admin/audit-log",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-30-audit-log.md",
  },
  {
    id: "SCR-ADM-31",
    title: "Admin users & roles",
    href: "/dev/screens/admin/admin-users",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-31-admin-users-roles.md",
  },
  {
    id: "SCR-ADM-32",
    title: "Coupons",
    href: "/dev/screens/admin/coupons",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-32-coupons.md",
  },
  {
    id: "SCR-ADM-33",
    title: "Admin notification inbox",
    href: "/dev/screens/admin/notifications",
    group: "admin",
    spec: "ui/screens/admin/SCR-ADM-33-notifications-inbox.md",
  },
];
