/**
 * Fixture data for the auth + account + checkout screen previews (/dev/screens/account/*).
 * Deterministic: `NOW` is fixed so relative times render identically on server and client.
 */
import type {
  AuthEvent,
  ChatMessage,
  ChatTranscript,
  CheckoutOffering,
  CustomerProfile,
  EntitlementDetail,
  InvoiceSummary,
  NotificationItem,
  OrderView,
  PaymentInstructions,
  PaymentSummary,
  QuerySummary,
  QuoteView,
  SessionInfo,
  WishlistItem,
} from "@/components/account/types";
import { money } from "@/lib/money";

export const NOW = "2026-09-25T09:30:00Z";

const inr = (paise: number) => money(paise, "INR");
const usd = (cents: number) => money(cents, "USD");

export const customer: CustomerProfile = {
  id: "usr_01",
  name: "Pravin Deshmukh",
  email: "pravin@iauro.com",
  emailVerified: true,
  initials: "PD",
  displayCurrency: "INR",
  themePref: null,
  reduceMotion: false,
  billing: {
    name: "Pravin Deshmukh",
    company: "iauro Systems Pvt Ltd",
    line1: "Office 402, Pride Icon",
    line2: "Kharadi",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411014",
    country: "IN",
    gstNumber: "27ABCDE1234F1Z5",
  },
};

export const paymentInstructions: PaymentInstructions = {
  upi: { vpa: "codekraft@icici", payeeName: "CodeKraft Studio" },
  bank: {
    accountName: "CodeKraft Studio",
    accountNumber: "0123 4567 8901 23",
    ifsc: "ICIC0001234",
    bankName: "ICICI Bank, Koregaon Park",
    swift: "ICICINBBXXX",
  },
};

export const entitlements: EntitlementDetail[] = [
  {
    id: "ent_download",
    productName: "FitDesk Pro",
    productHref: "/products/fitdesk-pro",
    offeringName: "Source bundle · Lifetime",
    deliveryType: "download",
    status: "active",
    provisioningState: "n/a",
    accessLabel: "Lifetime",
    secondaryLine: "3 of 5 downloads left",
    downloadsUsed: 2,
    downloadsCap: 5,
    purchasedAt: "2026-08-12T06:20:00Z",
    orderNumber: "CK-ORD-000009",
    invoiceNumber: "CK/2026-27/0009",
    updatePolicy: "all_free",
    versionOwned: "2.4.0",
    licenseType: "Single project",
    files: [
      {
        id: "f1",
        name: "fitdesk-pro-2.4.0.zip",
        version: "2.4.0",
        sizeLabel: "48.2 MB",
        releasedAt: "2026-09-20T10:00:00Z",
      },
      {
        id: "f2",
        name: "fitdesk-pro-2.3.1.zip",
        version: "2.3.1",
        sizeLabel: "47.9 MB",
        releasedAt: "2026-07-02T10:00:00Z",
      },
      {
        id: "f3",
        name: "fitdesk-pro-2.3.0.zip",
        version: "2.3.0",
        sizeLabel: "47.1 MB",
        releasedAt: "2026-05-15T10:00:00Z",
      },
    ],
    changelog: [
      {
        version: "2.4.0",
        date: "2026-09-20T10:00:00Z",
        notes: ["Standing-desk presets", "Fixes timer drift on Safari", "Node 22 build target"],
      },
      {
        version: "2.3.1",
        date: "2026-07-02T10:00:00Z",
        notes: ["Security patch for the export CLI"],
      },
    ],
    instructions: [
      "Unzip the bundle and run `pnpm install` inside the project folder.",
      "Copy `.env.example` to `.env` and set your database URL before the first `pnpm dev`.",
    ],
  },
  {
    id: "ent_license",
    productName: "Ledgerly Desktop",
    productHref: "/products/ledgerly",
    offeringName: "Business licence · 12 months",
    deliveryType: "license",
    status: "active",
    provisioningState: "n/a",
    accessLabel: "Until 12 Mar 2027",
    secondaryLine: "Key available",
    keyIssued: true,
    purchasedAt: "2026-03-12T08:00:00Z",
    accessEndsAt: "2027-03-12T08:00:00Z",
    orderNumber: "CK-ORD-000004",
    invoiceNumber: "CK/2025-26/0041",
    updatePolicy: "during_access",
    versionOwned: "5.1",
    licenseType: "Business · 3 machines",
    licenseKey: { masked: "•••• •••• •••• 4F2A", full: "LDGR-8H2K-PQ7M-9XZ1-4F2A" },
    instructions: [
      "Open Ledgerly, choose Help › Activate and paste the key.",
      "Activation needs an internet connection once; the app then works offline for 30 days at a time.",
    ],
  },
  {
    id: "ent_saas",
    productName: "Roster Cloud",
    productHref: "/products/roster-cloud",
    offeringName: "Team workspace",
    deliveryType: "saas",
    status: "active",
    provisioningState: "pending",
    accessLabel: "Renews 3 Oct · monthly",
    secondaryLine: "Being set up — we'll notify you",
    purchasedAt: "2026-09-24T14:05:00Z",
    orderNumber: "CK-ORD-000012",
    invoiceNumber: "CK/2026-27/0012",
    updatePolicy: "during_access",
    hosted: {
      loginUrl: "https://app.rostercloud.example/login",
      username: "pravin@iauro.com",
      credentialsSentAt: "2026-09-24T14:30:00Z",
      expectedBy: "2026-09-26T14:00:00Z",
    },
    subscription: {
      interval: "monthly",
      status: "active",
      currentPeriodEnd: "2026-10-03T00:00:00Z",
      nextDue: inr(99_900),
      cancelAtPeriodEnd: false,
      renewable: true,
    },
    instructions: [
      "Your workspace URL and a first-login link arrive by email once provisioning completes.",
    ],
  },
  {
    id: "ent_service",
    productName: "Storefront Kit",
    productHref: "/products/storefront-kit",
    offeringName: "Kit + installation service",
    deliveryType: "service",
    status: "active",
    provisioningState: "n/a",
    accessLabel: "Lifetime",
    secondaryLine: "Step 2 of 4 complete",
    stepsDone: 2,
    stepsTotal: 4,
    purchasedAt: "2026-09-10T11:00:00Z",
    orderNumber: "CK-ORD-000011",
    invoiceNumber: "CK/2026-27/0011",
    updatePolicy: "major_paid",
    versionOwned: "1.8",
    steps: [
      {
        id: "s1",
        title: "Kick-off call",
        description: "30-minute call to collect hosting and domain details.",
        state: "done",
        doneAt: "2026-09-11T09:00:00Z",
      },
      {
        id: "s2",
        title: "Environment set up",
        description: "Database, object storage and secrets configured on your host.",
        state: "done",
        doneAt: "2026-09-15T13:20:00Z",
        note: "Deployed to Hetzner CX22 as requested.",
      },
      {
        id: "s3",
        title: "Theme and catalogue import",
        description: "Your products and brand assets loaded into the storefront.",
        state: "in_progress",
      },
      {
        id: "s4",
        title: "Handover and training",
        description: "Walk-through recording and admin credentials.",
        state: "open",
      },
    ],
    instructions: ["We'll email you before each step that needs your input."],
  },
  {
    id: "ent_hosted_sub",
    productName: "Metrics Board",
    productHref: "/products/metrics-board",
    offeringName: "Hosted · Annual",
    deliveryType: "hosted",
    status: "suspended",
    provisioningState: "done",
    accessLabel: "Past due since 20 Sep 2026",
    secondaryLine: "Suspended — payment overdue",
    purchasedAt: "2025-09-20T08:00:00Z",
    orderNumber: "CK-ORD-000002",
    invoiceNumber: "CK/2025-26/0002",
    updatePolicy: "during_access",
    hosted: {
      loginUrl: "https://metrics.codekraft.example",
      username: "pravin",
      credentialsSentAt: "2025-09-21T08:00:00Z",
    },
    subscription: {
      interval: "annual",
      status: "past_due",
      currentPeriodEnd: "2026-09-20T08:00:00Z",
      nextDue: inr(1_499_900),
      cancelAtPeriodEnd: false,
      renewable: true,
    },
    instructions: ["Sign in with the username above; password resets happen inside the app."],
  },
];

export const expiredEntitlement: EntitlementDetail = {
  id: "ent_expired",
  productName: "Ledgerly Desktop",
  offeringName: "Starter licence · 12 months",
  deliveryType: "license",
  status: "expired",
  provisioningState: "n/a",
  accessLabel: "Ended 1 Mar 2026",
  purchasedAt: "2025-03-01T08:00:00Z",
  accessEndsAt: "2026-03-01T08:00:00Z",
  orderNumber: "CK-ORD-000001",
  updatePolicy: "during_access",
  instructions: [],
};

export const invoices: InvoiceSummary[] = [
  {
    id: "inv_12",
    kind: "invoice",
    number: "CK/2026-27/0012",
    date: "2026-09-24T14:05:00Z",
    orderNumber: "CK-ORD-000012",
    description: "Roster Cloud · Team workspace",
    amount: inr(117_882),
    displayAmount: usd(1_416),
    tax: inr(17_982),
    status: "paid",
  },
  {
    id: "inv_11",
    kind: "invoice",
    number: "CK/2026-27/0011",
    date: "2026-09-10T11:00:00Z",
    orderNumber: "CK-ORD-000011",
    description: "Storefront Kit · Kit + installation service",
    amount: inr(4_720_000),
    displayAmount: usd(56_700),
    tax: inr(720_000),
    status: "paid",
  },
  {
    id: "cn_3",
    kind: "credit_note",
    number: "CN/2026-27/0003",
    forInvoiceNumber: "CK/2026-27/0009",
    date: "2026-08-30T09:00:00Z",
    orderNumber: "CK-ORD-000009",
    description: "Partial refund · FitDesk Pro add-on",
    amount: inr(-59_000),
    tax: null,
    status: "partially_refunded",
  },
];

export const payments: PaymentSummary[] = [
  {
    id: "pay_13",
    date: "2026-09-25T07:10:00Z",
    orderNumber: "CK-ORD-000013",
    orderHref: "/account/orders/ord_13",
    provider: "manual_upi",
    amountDue: inr(1_180_000),
    status: "initiated",
    orderOpen: true,
  },
  {
    id: "pay_12",
    date: "2026-09-24T14:05:00Z",
    orderNumber: "CK-ORD-000012",
    orderHref: "/account/orders/ord_12",
    provider: "manual_bank",
    amountDue: inr(117_882),
    reference: "ICIC24092612345",
    status: "confirmed",
    orderOpen: false,
  },
  {
    id: "pay_10",
    date: "2026-09-01T10:00:00Z",
    orderNumber: "CK-ORD-000010",
    orderHref: "/account/orders/ord_10",
    provider: "manual_upi",
    amountDue: inr(99_900),
    status: "failed",
    orderOpen: false,
  },
];

const pendingBase: OrderView = {
  id: "ord_13",
  number: "CK-ORD-000013",
  placedAt: "2026-09-25T07:10:00Z",
  status: "pending_payment",
  expiresAt: "2026-10-02T07:10:00Z",
  productName: "Storefront Kit",
  offeringName: "Kit + installation service",
  purchaseModelLine: "One-time · lifetime access",
  deliveryType: "service",
  lines: [
    {
      name: "Storefront Kit · Kit + installation service",
      unit: inr(1_000_000),
      quantity: 1,
      taxLabel: "GST 18%",
      total: inr(1_180_000),
    },
  ],
  subtotal: inr(1_000_000),
  tax: inr(180_000),
  total: inr(1_180_000),
  displayTotal: usd(14_160),
  billing: customer.billing,
  paymentMethod: "manual_upi",
  enabledMethods: ["manual_upi", "manual_bank"],
  instructionsFor: paymentInstructions,
  payment: { status: "initiated" },
  refundable: false,
};

export const orders = {
  awaitingReference: pendingBase,
  submitted: {
    ...pendingBase,
    payment: { status: "submitted", reference: "426119384712", paidOn: "2026-09-25T08:00:00Z" },
  } satisfies OrderView,
  confirmed: {
    ...pendingBase,
    id: "ord_12",
    number: "CK-ORD-000012",
    placedAt: "2026-09-24T14:05:00Z",
    status: "fulfilled",
    expiresAt: undefined,
    productName: "Roster Cloud",
    offeringName: "Team workspace",
    purchaseModelLine: "Monthly subscription · renews every month",
    deliveryType: "saas",
    lines: [
      {
        name: "Roster Cloud · Team workspace",
        unit: inr(99_900),
        quantity: 1,
        taxLabel: "GST 18%",
        total: inr(117_882),
      },
    ],
    subtotal: inr(99_900),
    tax: inr(17_982),
    total: inr(117_882),
    displayTotal: usd(1_416),
    paymentMethod: "manual_bank",
    payment: {
      status: "confirmed",
      reference: "ICIC24092612345",
      paidOn: "2026-09-24T15:00:00Z",
      confirmedAt: "2026-09-24T18:40:00Z",
      received: inr(117_732),
      shortfall: inr(150),
    },
    refundable: true,
    entitlementId: "ent_saas",
    invoiceNumber: "CK/2026-27/0012",
    postPurchaseInstructions: [
      "Your workspace is being provisioned. You'll get an email with the login link within one working day.",
    ],
  } satisfies OrderView,
  failedAttempt: {
    ...pendingBase,
    payment: {
      status: "failed",
      reference: "426119384712",
      failureReason:
        "Amount received did not match the order (₹1,000 short). Please pay the full amount.",
    },
  } satisfies OrderView,
  expired: {
    ...pendingBase,
    id: "ord_10",
    number: "CK-ORD-000010",
    placedAt: "2026-09-01T10:00:00Z",
    status: "failed",
    expiresAt: "2026-09-08T10:00:00Z",
    failedReason: "expired",
    payment: { status: "failed" },
  } satisfies OrderView,
  refunded: {
    ...pendingBase,
    id: "ord_09",
    number: "CK-ORD-000009",
    placedAt: "2026-08-12T06:20:00Z",
    status: "partially_refunded",
    expiresAt: undefined,
    productName: "FitDesk Pro",
    offeringName: "Source bundle · Lifetime",
    deliveryType: "download",
    payment: { status: "refunded", reference: "426110000001", confirmedAt: "2026-08-12T12:00:00Z" },
    refund: { amount: inr(59_000), creditNoteNumber: "CN/2026-27/0003" },
    refundable: true,
    entitlementId: "ent_download",
    invoiceNumber: "CK/2026-27/0009",
  } satisfies OrderView,
} as const;

export type OrderPreviewState = keyof typeof orders;

export const queries: QuerySummary[] = [
  {
    id: "q_31",
    subject: "Install issue on Windows 11",
    preview: "Priya: Can you send the log from %APPDATA%\\Ledgerly\\logs?",
    status: "waiting_customer",
    source: "dashboard",
    relatedLabel: "Ledgerly Desktop",
    relatedHref: "/account/purchases/ent_license",
    lastActivityAt: "2026-09-25T06:45:00Z",
    unread: true,
    messages: [
      {
        id: "m1",
        author: "customer",
        body: "The installer stops at 80% with error 0x8007. I'm on Windows 11 23H2.",
        at: "2026-09-24T16:10:00Z",
        attachments: [{ name: "installer-screenshot.png", sizeLabel: "312 KB" }],
      },
      {
        id: "m2",
        author: "admin",
        authorName: "Priya",
        body: "Thanks Pravin — that code usually means a locked temp folder. Can you send the log from %APPDATA%\\Ledgerly\\logs? We usually reply within 1 working day.",
        at: "2026-09-25T06:45:00Z",
      },
    ],
  },
  {
    id: "q_30",
    subject: "Refund request · CK-ORD-000009",
    preview: "System: Refund of ₹590.00 approved — credit note CN/2026-27/0003 issued.",
    status: "resolved",
    source: "order",
    relatedLabel: "CK-ORD-000009",
    relatedHref: "/account/orders/ord_09",
    lastActivityAt: "2026-08-30T09:00:00Z",
    unread: false,
    messages: [
      {
        id: "m3",
        author: "system",
        body: "Refund requested for ₹590.00 (add-on line). This product is refundable within our policy.",
        at: "2026-08-28T10:00:00Z",
      },
      {
        id: "m4",
        author: "customer",
        body: "I bought the analytics add-on by mistake; the base bundle is all I need.",
        at: "2026-08-28T10:01:00Z",
      },
      {
        id: "m5",
        author: "admin",
        authorName: "Arjun",
        body: "No problem — approved. The credit note will be in Invoices & payments shortly.",
        at: "2026-08-29T12:30:00Z",
      },
      {
        id: "m6",
        author: "system",
        body: "Refund of ₹590.00 approved — credit note CN/2026-27/0003 issued.",
        at: "2026-08-30T09:00:00Z",
      },
    ],
  },
];

export const chatTranscripts: ChatTranscript[] = [
  {
    id: "c_2",
    startedAt: "2026-09-20T08:00:00Z",
    preview: "Where is my licence key?",
    escalated: false,
  },
  {
    id: "c_1",
    startedAt: "2026-09-02T11:00:00Z",
    preview: "Can Storefront Kit run on shared hosting?",
    escalated: true,
  },
];

export const chatMenu = ["Order status", "Downloads", "Renewal", "Invoices", "Contact"];

export const chatMessages: ChatMessage[] = [
  {
    id: "cm1",
    role: "assistant",
    text: "Hi Pravin. I can check your orders, downloads and renewals, or answer questions about our products and services. What do you need?",
    at: "2026-09-25T09:00:00Z",
  },
  { id: "cm2", role: "menu", chips: chatMenu, at: "2026-09-25T09:00:01Z" },
  { id: "cm3", role: "user", text: "Order status", at: "2026-09-25T09:01:00Z" },
  {
    id: "cm4",
    role: "assistant",
    text: "Here's your latest order:",
    card: {
      kind: "order",
      orderNumber: "CK-ORD-000013",
      status: "pending_payment",
      steps: [
        { label: "Placed", done: true },
        { label: "Paid", done: false },
        { label: "Confirmed by us", done: false },
        { label: "Access ready", done: false },
      ],
      href: "/account/orders/ord_13",
    },
    at: "2026-09-25T09:01:02Z",
  },
  {
    id: "cm5",
    role: "user",
    text: "Does FitDesk Pro include a refund window?",
    at: "2026-09-25T09:02:00Z",
  },
  {
    id: "cm6",
    role: "assistant",
    text: "Yes — FitDesk Pro is refundable within 14 days of purchase as long as no more than one download has been made. Refund requests go through the order page and our team reviews them within one working day.",
    citations: [
      { label: "FitDesk Pro · Refund policy", href: "/products/fitdesk-pro#refunds" },
      { label: "Refund & cancellation policy", href: "/legal/refunds" },
    ],
    at: "2026-09-25T09:02:04Z",
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "n1",
    type: "orders",
    title: "Order CK-ORD-000013 awaits your payment",
    body: "Storefront Kit · pay ₹11,800.00 by 2 Oct to keep the order.",
    at: "2026-09-25T07:12:00Z",
    read: false,
    href: "/account/orders/ord_13",
    actionLabel: "Submit reference",
  },
  {
    id: "n2",
    type: "queries",
    title: "CodeKraft replied to 'Install issue on Windows 11'",
    body: "Priya: Can you send the log from %APPDATA%\\Ledgerly\\logs?",
    at: "2026-09-25T06:45:00Z",
    read: false,
    href: "/account/queries/q_31",
  },
  {
    id: "n3",
    type: "delivery",
    title: "Payment confirmed",
    body: "Roster Cloud · Team workspace is being set up.",
    at: "2026-09-24T18:40:00Z",
    read: false,
    href: "/account/orders/ord_12",
  },
  {
    id: "n4",
    type: "renewals",
    title: "Renewal due in 7 days",
    body: "Metrics Board · Annual renews on 3 Oct for ₹14,999.00.",
    at: "2026-09-24T08:00:00Z",
    read: true,
    href: "/account/purchases/ent_hosted_sub",
    actionLabel: "Renew",
  },
  {
    id: "n5",
    type: "product_updates",
    title: "FitDesk Pro 2.4 released",
    body: "Standing-desk presets and a Safari timer fix. Included in your update policy.",
    at: "2026-09-20T10:05:00Z",
    read: true,
    href: "/account/purchases/ent_download",
  },
  {
    id: "n6",
    type: "delivery",
    title: "Your license key is ready",
    body: "Ledgerly Desktop · Business licence key issued.",
    at: "2026-03-12T08:30:00Z",
    read: true,
    href: "/account/purchases/ent_license",
    actionLabel: "Reveal key",
  },
];

export const wishlist: WishlistItem[] = [
  {
    id: "w1",
    productName: "Invoice Forge",
    category: "Finance tools",
    productHref: "/products/invoice-forge",
    fromPrice: inr(499_900),
    priceDropped: true,
    addedAt: "2026-09-18T10:00:00Z",
  },
  {
    id: "w2",
    productName: "Roster Cloud",
    category: "Team SaaS",
    productHref: "/products/roster-cloud",
    fromPrice: inr(99_900),
    owned: true,
    addedAt: "2026-09-01T10:00:00Z",
  },
  {
    id: "w3",
    productName: "Kiln CMS",
    category: "Content",
    productHref: "/products/kiln-cms",
    comingSoon: true,
    addedAt: "2026-08-20T10:00:00Z",
  },
  {
    id: "w4",
    productName: "FitDesk Pro",
    category: "Productivity",
    productHref: "/products/fitdesk-pro",
    fromPrice: inr(590_000),
    newVersion: true,
    addedAt: "2026-08-02T10:00:00Z",
  },
  {
    id: "w5",
    productName: "Warehouse Sync",
    category: "Integrations",
    productHref: "/products/warehouse-sync",
    customQuote: true,
    addedAt: "2026-07-14T10:00:00Z",
  },
  {
    id: "w6",
    productName: "Legacy Reports",
    category: "Finance tools",
    productHref: "/products/legacy-reports",
    unavailable: true,
    addedAt: "2026-05-01T10:00:00Z",
  },
];

export const quote: QuoteView = {
  token: "qt_8f3a",
  title: "Warehouse Sync · custom integration for iauro",
  preparedFor: "Pravin Deshmukh",
  validUntil: "2026-10-09T18:29:59Z",
  status: "sent",
  description: [
    "Two-way stock sync between your Zoho Inventory account and the Storefront Kit catalogue, with nightly reconciliation and a Slack alert on mismatches.",
    "Includes deployment to your existing Hetzner host and 30 days of fixes after handover.",
  ],
  product: { name: "Warehouse Sync", offeringName: "Custom integration", deliveryType: "custom" },
  amount: inr(8_260_000),
  displayAmount: usd(99_100),
  tax: inr(1_260_000),
  taxLabel: "GST 18%",
  includes: [
    "Zoho Inventory ↔ catalogue sync (SKU, stock, price)",
    "Nightly reconciliation report",
    "Slack alerts on mismatch",
    "Deployment + 30-day fix window",
  ],
  paymentMethods: ["manual_upi", "manual_bank"],
};

export const checkoutOffering: CheckoutOffering = {
  productName: "Storefront Kit",
  offeringName: "Kit + installation service",
  purchaseModelLine: "One-time · lifetime access",
  deliveryType: "service",
  unit: inr(1_000_000),
  taxLabel: "GST 18%",
  tax: inr(180_000),
  enabledMethods: ["manual_upi", "manual_bank"],
  displayCurrency: "USD",
  displayEstimate: usd(14_160),
  productHref: "/products/storefront-kit",
};

export const session: SessionInfo = {
  device: "Chrome on macOS · Pune, IN",
  ip: "103.21.xx.xx",
  lastActiveAt: "2026-09-25T09:28:00Z",
};

export const authEvents: AuthEvent[] = [
  { id: "a1", kind: "login", at: "2026-09-25T09:00:00Z", device: "Chrome on macOS" },
  { id: "a2", kind: "session_replaced", at: "2026-09-23T19:12:00Z", device: "Safari on iPhone" },
  { id: "a3", kind: "login", at: "2026-09-23T19:12:00Z", device: "Safari on iPhone" },
  { id: "a4", kind: "logout", at: "2026-09-20T17:40:00Z", device: "Chrome on macOS" },
  { id: "a5", kind: "password_reset", at: "2026-08-02T08:15:00Z", device: "Chrome on macOS" },
];
