/**
 * Fixture data for the admin screen previews (/dev/screens/admin/*). INR amounts are paise.
 * Everything here is placeholder content; Phase 8 replaces it with Server Action results.
 */
import type {
  AdjustmentRow,
  AdminNotification,
  AdminUserRef,
  AdminUserRow,
  AllocationRow,
  ApprovalItem,
  AuditRow,
  CaseStudyRow,
  CategoryNode,
  ChatbotMonitorData,
  ClientLogo,
  CouponRow,
  CustomerCreditRow,
  CustomerDetailData,
  CustomerRow,
  DashboardData,
  DeliveryTaskRow,
  EntitlementRow,
  ExpenseRow,
  FaqItem,
  LandingChapter,
  LeadDetailData,
  LeadRow,
  LedgerEntry,
  LegalPage,
  OfferingOption,
  OrderDetailData,
  OrderRow,
  PartnerBalance,
  PayoutRow,
  ProductEditorData,
  ProductRow,
  QueryRow,
  QueryThread,
  QuoteRow,
  ReportDefinition,
  SearchItem,
  ServiceRow,
  SettingsData,
  StatementHistoryRow,
  StatementPreview,
  TestimonialItem,
} from "@/components/admin/types";

export const NOW = "2026-09-25T09:30:00.000Z";

const inr = (paise: number) => ({ amountMinor: paise, currency: "INR" as const });
const usd = (cents: number) => ({ amountMinor: cents, currency: "USD" as const });

export const PRIYA: AdminUserRef = {
  id: "u-priya",
  name: "Priya Nair",
  email: "priya@codekraft.in",
  role: "super_admin",
};
export const ARJUN: AdminUserRef = {
  id: "u-arjun",
  name: "Arjun Mehta",
  email: "arjun@codekraft.in",
  role: "super_admin",
};
export const CURRENT_ADMIN = PRIYA;
export const ADMINS = [PRIYA, ARJUN];
export const PARTNERS = [
  { id: "p-priya", name: "Priya Nair" },
  { id: "p-arjun", name: "Arjun Mehta" },
];

/** Preview routes stand in for the real admin routes (docs/07 §2.4). */
export const PREVIEW_ROUTES: Record<string, string> = {
  "/login": "/dev/screens/admin/login",
  "/dashboard": "/dev/screens/admin/dashboard",
  "/approvals": "/dev/screens/admin/approvals",
  "/notifications": "/dev/screens/admin/notifications",
  "/products": "/dev/screens/admin/products",
  "/products/new": "/dev/screens/admin/product-editor",
  "/categories": "/dev/screens/admin/products",
  "/coupons": "/dev/screens/admin/coupons",
  "/orders": "/dev/screens/admin/orders",
  "/orders/new": "/dev/screens/admin/manual-order",
  "/quotes": "/dev/screens/admin/quotes",
  "/customers": "/dev/screens/admin/customers",
  "/entitlements": "/dev/screens/admin/entitlements",
  "/delivery-tasks": "/dev/screens/admin/entitlements",
  "/leads": "/dev/screens/admin/leads",
  "/queries": "/dev/screens/admin/queries",
  "/chatbot": "/dev/screens/admin/chatbot",
  "/finance/ledger": "/dev/screens/admin/finance-ledger",
  "/finance/allocations": "/dev/screens/admin/finance-allocations",
  "/finance/partners": "/dev/screens/admin/finance-partners",
  "/finance/expenses": "/dev/screens/admin/finance-expenses",
  "/finance/adjustments": "/dev/screens/admin/finance-adjustments",
  "/finance/reports": "/dev/screens/admin/finance-reports",
  "/content/landing": "/dev/screens/admin/content-landing",
  "/content/services": "/dev/screens/admin/content-services",
  "/content/case-studies": "/dev/screens/admin/content-case-studies",
  "/content/testimonials": "/dev/screens/admin/content-testimonials",
  "/content/faqs": "/dev/screens/admin/content-faqs",
  "/content/legal": "/dev/screens/admin/content-legal",
  "/settings": "/dev/screens/admin/settings",
  "/audit": "/dev/screens/admin/audit-log",
  "/admin-users": "/dev/screens/admin/admin-users",
};
export const href = (route: string): string =>
  PREVIEW_ROUTES[route] ?? `/dev/screens/admin${route}`;

export const NOTIFICATIONS: AdminNotification[] = [
  {
    id: "n1",
    type: "payments",
    title: "Payment reference submitted · CK-ORD-000012",
    body: "UPI · ₹7,999.00 · ravi@example.com",
    at: "2026-09-25T08:52:00Z",
    read: false,
    href: href("/orders"),
    action: { label: "Confirm payment", href: href("/orders"), readMostly: true },
  },
  {
    id: "n2",
    type: "approvals",
    title: "Arjun requested approval: publish MIS Portal",
    body: "Readiness checks passed · publish at 1 Oct",
    at: "2026-09-25T07:10:00Z",
    read: false,
    href: href("/approvals"),
    action: { label: "Review approval", href: href("/approvals"), readMostly: true },
  },
  {
    id: "n3",
    type: "leads",
    title: "New lead · Acme Ltd (product CTA)",
    body: "FitDesk Pro · wants a customised rollout for 40 seats",
    at: "2026-09-25T06:40:00Z",
    read: false,
    href: href("/leads"),
    action: { label: "Claim lead", href: href("/leads") },
  },
  {
    id: "n4",
    type: "queries",
    title: "Customer replied · Download cap reached",
    body: "Meera Shah · TradeFlow · 5/5 downloads used",
    at: "2026-09-24T18:05:00Z",
    read: false,
    href: href("/queries"),
    action: { label: "Open query", href: href("/queries") },
  },
  {
    id: "n5",
    type: "delivery",
    title: "Provision account for FitDesk Pro · ravi@example.com",
    body: "Task open since 2 d · assigned to you",
    at: "2026-09-23T09:00:00Z",
    read: false,
    href: href("/entitlements"),
    action: { label: "Mark task done", href: href("/entitlements") },
  },
  {
    id: "n6",
    type: "chatbot",
    title: "Daily chat cap reached",
    body: "2,000 / 2,000 platform messages · menu-only until midnight IST",
    at: "2026-09-24T15:20:00Z",
    read: true,
    href: href("/chatbot"),
  },
  {
    id: "n7",
    type: "system",
    title: "Job orders.expire failed",
    body: "Timeout after 30 s · 2 pending orders not expired",
    at: "2026-09-24T02:00:00Z",
    read: true,
    href: href("/settings"),
  },
  {
    id: "n8",
    type: "approvals",
    title: "Priya approved: payout to Arjun Mehta",
    body: "₹42,000.00 · posted as ledger seq 1088",
    at: "2026-09-23T14:30:00Z",
    read: true,
    href: href("/finance-partners"),
  },
  {
    id: "n9",
    type: "leads",
    title: "Follow-up overdue · Nimbus Retail",
    body: "Was due 3 days ago · assigned to Arjun",
    at: "2026-09-22T09:00:00Z",
    read: true,
    href: href("/leads"),
  },
  {
    id: "n10",
    type: "payments",
    title: "Payment reference submitted · CK-ORD-000009",
    body: "Bank transfer · ₹24,999.00 · Global Textiles",
    at: "2026-09-21T11:15:00Z",
    read: true,
    href: href("/orders"),
  },
];

export const SEARCH_ITEMS: SearchItem[] = [
  { group: "Products", label: "FitDesk Pro", hint: "Published · SaaS", href: href("/products") },
  { group: "Products", label: "TradeFlow", hint: "Published · Download", href: href("/products") },
  { group: "Products", label: "MIS Portal", hint: "Pending approval", href: href("/products") },
  { group: "Orders", label: "CK-ORD-000012", hint: "Awaiting confirmation", href: href("/orders") },
  { group: "Orders", label: "CK-ORD-000009", hint: "Paid", href: href("/orders") },
  { group: "Customers", label: "ravi@example.com", hint: "Ravi Kumar", href: href("/customers") },
  {
    group: "Customers",
    label: "meera@shahdesigns.in",
    hint: "Meera Shah",
    href: href("/customers"),
  },
  { group: "Leads", label: "Acme Ltd", hint: "New · product CTA", href: href("/leads") },
  { group: "Go to", label: "Approvals", href: href("/approvals") },
  { group: "Go to", label: "Ledger", href: href("/finance/ledger") },
  { group: "Go to", label: "Settings", href: href("/settings") },
];

/* ------------------------------------------------------------------ catalog */

export const PRODUCTS: ProductRow[] = [
  {
    id: "prod-1",
    name: "FitDesk Pro",
    slug: "fitdesk-pro",
    category: "SaaS › Productivity",
    status: "published",
    flags: ["is_featured", "is_refundable", "tax_enabled"],
    offerings: 3,
    fromPrice: inr(99900),
    version: "2.4.0",
    updatedAt: "2026-09-24T16:10:00Z",
    updatedBy: "Priya",
    orderCount: 42,
  },
  {
    id: "prod-2",
    name: "TradeFlow",
    slug: "tradeflow",
    category: "Downloads › Finance",
    status: "published",
    flags: ["tax_enabled"],
    offerings: 2,
    fromPrice: inr(2499900),
    version: "1.8.2",
    updatedAt: "2026-09-22T11:00:00Z",
    updatedBy: "Arjun",
    orderCount: 17,
  },
  {
    id: "prod-3",
    name: "MIS Portal",
    slug: "mis-portal",
    category: "Services › Implementation",
    status: "pending_approval",
    flags: [],
    offerings: 1,
    fromPrice: inr(12000000),
    version: "1.0.0",
    updatedAt: "2026-09-25T07:05:00Z",
    updatedBy: "Arjun",
    awaitingApprovalId: "apr-1",
    orderCount: 3,
  },
  {
    id: "prod-4",
    name: "Ledgerly",
    slug: "ledgerly",
    category: "SaaS › Finance",
    status: "draft",
    flags: ["is_coming_soon"],
    offerings: 0,
    version: "0.1.0",
    updatedAt: "2026-09-20T09:30:00Z",
    updatedBy: "Priya",
    orderCount: 0,
  },
  {
    id: "prod-5",
    name: "InvoiceKit",
    slug: "invoicekit",
    category: "Downloads › Finance",
    status: "scheduled",
    flags: ["is_refundable"],
    offerings: 2,
    fromPrice: inr(499900),
    version: "1.0.0",
    updatedAt: "2026-09-19T14:45:00Z",
    updatedBy: "Priya",
    orderCount: 0,
  },
  {
    id: "prod-6",
    name: "ShopSync",
    slug: "shopsync",
    category: "SaaS › Commerce",
    status: "unpublished",
    flags: ["is_unlisted"],
    offerings: 1,
    fromPrice: inr(149900),
    version: "3.2.1",
    updatedAt: "2026-08-30T10:00:00Z",
    updatedBy: "Arjun",
    orderCount: 11,
  },
  {
    id: "prod-7",
    name: "OldCRM",
    slug: "oldcrm",
    category: "SaaS › Sales",
    status: "archived",
    flags: [],
    offerings: 1,
    fromPrice: inr(79900),
    version: "4.0.0",
    updatedAt: "2026-06-01T08:00:00Z",
    updatedBy: "Priya",
    orderCount: 58,
  },
  {
    id: "prod-8",
    name: "Brand Kit Templates",
    slug: "brand-kit",
    category: "Downloads › Design",
    status: "published",
    flags: ["is_unlisted", "is_refundable"],
    offerings: 1,
    fromPrice: inr(29900),
    version: "1.2.0",
    updatedAt: "2026-09-10T12:20:00Z",
    updatedBy: "Priya",
    orderCount: 6,
  },
];

export const CATEGORIES: CategoryNode[] = [
  {
    id: "c-saas",
    name: "SaaS",
    slug: "saas",
    productCount: 5,
    children: [
      { id: "c-prod", name: "Productivity", slug: "productivity", productCount: 1 },
      { id: "c-fin", name: "Finance", slug: "finance", productCount: 1 },
      { id: "c-com", name: "Commerce", slug: "commerce", productCount: 1 },
      { id: "c-sales", name: "Sales", slug: "sales", productCount: 1 },
    ],
  },
  {
    id: "c-dl",
    name: "Downloads",
    slug: "downloads",
    productCount: 3,
    children: [
      { id: "c-dl-fin", name: "Finance", slug: "finance", productCount: 2 },
      { id: "c-dl-des", name: "Design", slug: "design", productCount: 1 },
    ],
  },
  {
    id: "c-svc",
    name: "Services",
    slug: "services",
    productCount: 1,
    children: [{ id: "c-impl", name: "Implementation", slug: "implementation", productCount: 1 }],
  },
];

export const TAGS = [
  "automation",
  "finance",
  "gst",
  "react",
  "self-hosted",
  "starter",
  "teams",
  "templates",
];

export const PRODUCT_EDITOR: ProductEditorData = {
  id: "prod-1",
  name: "FitDesk Pro",
  slug: "fitdesk-pro",
  shortDescription: "Standing-desk scheduling and wellness nudges for hybrid teams.",
  category: "SaaS › Productivity",
  tags: ["teams", "automation"],
  status: "published",
  flags: ["is_featured", "is_refundable", "tax_enabled"],
  currentVersion: "2.4.0",
  description:
    "FitDesk Pro schedules sit-stand cycles per employee, integrates with calendar tools and reports wellness metrics to team leads.",
  features: [
    "Calendar-aware sit-stand reminders",
    "Team dashboards",
    "Slack and Teams nudges",
    "CSV export",
  ],
  benefits: ["Fewer back complaints", "Measurable posture habits"],
  techStack: ["Next.js", "Postgres", "Redis"],
  liveDemoUrl: "https://demo.fitdesk.example",
  media: [
    {
      id: "m1",
      kind: "image",
      fileName: "hero-cover.webp",
      alt: "FitDesk Pro dashboard on a laptop",
      sizeKb: 118,
    },
    {
      id: "m2",
      kind: "screenshot",
      fileName: "team-view.png",
      alt: "Team standing-time report",
      sizeKb: 310,
    },
    { id: "m3", kind: "video_embed", fileName: "youtube.com/watch?v=fd-pro", sizeKb: 0 },
    { id: "m4", kind: "presentation", fileName: "fitdesk-overview.pdf", sizeKb: 2400 },
  ],
  storageUsedMb: 214,
  storageCapMb: 2048,
  offerings: [
    {
      id: "off-1",
      name: "Starter",
      purchaseModel: "subscription",
      billingInterval: "monthly",
      deliveryType: "saas",
      basePrice: inr(99900),
      methods: ["upi", "bank"],
      status: "active",
      isDefault: true,
    },
    {
      id: "off-2",
      name: "Team",
      purchaseModel: "subscription",
      billingInterval: "annual",
      deliveryType: "saas",
      basePrice: inr(999900),
      compareAt: inr(1198800),
      methods: ["upi", "bank"],
      status: "active",
      isDefault: false,
    },
    {
      id: "off-3",
      name: "Enterprise rollout",
      purchaseModel: "custom_quote",
      deliveryType: "service",
      basePrice: inr(0),
      methods: ["bank"],
      status: "active",
      isDefault: false,
    },
  ],
  ownership: [
    {
      version: 2,
      companyCutBps: 2000,
      lines: [
        { partnerId: "p-priya", partnerName: "Priya Nair", bps: 5000 },
        { partnerId: "p-arjun", partnerName: "Arjun Mehta", bps: 3000 },
      ],
      effectiveFrom: "2026-08-01",
      status: "active",
    },
    {
      version: 1,
      companyCutBps: 2000,
      lines: [
        { partnerId: "p-priya", partnerName: "Priya Nair", bps: 4000 },
        { partnerId: "p-arjun", partnerName: "Arjun Mehta", bps: 4000 },
      ],
      effectiveFrom: "2026-03-01",
      status: "superseded",
    },
  ],
  partners: PARTNERS,
  seo: {
    title: "FitDesk Pro — sit-stand scheduling for teams",
    description:
      "Schedule standing time across your team, nudge in Slack and report posture habits.",
    canonical: "https://codekraft.example/products/fitdesk-pro",
  },
  blog: {
    title: "Why standing meetings failed and what we did next",
    slug: "standing-meetings",
    excerpt: "A short history of our sit-stand experiments.",
    status: "published",
  },
  versions: [
    {
      version: "2.4.0",
      releasedAt: "2026-09-20",
      files: 2,
      changelog: "Teams nudges, CSV export.",
    },
    {
      version: "2.3.1",
      releasedAt: "2026-07-02",
      files: 2,
      changelog: "Fixes calendar sync drift.",
    },
    { version: "2.0.0", releasedAt: "2026-03-01", files: 1, changelog: "Team dashboards." },
  ],
  testimonials: [
    {
      id: "t1",
      quote: "Our support tickets about back pain dropped to zero within a month.",
      author: "Kavya R.",
      title: "People ops lead",
      company: "Nimbus Retail",
      context: "product",
      published: true,
    },
    {
      id: "t2",
      quote: "The Slack nudges are just annoying enough to work.",
      author: "Dev S.",
      title: "Engineering manager",
      company: "Acme Ltd",
      context: "product",
      published: false,
    },
  ],
  faqs: [
    {
      id: "f1",
      question: "Does FitDesk Pro need a hardware desk controller?",
      answer: "No. It schedules and nudges; any desk works.",
      scope: "product",
      published: true,
    },
    {
      id: "f2",
      question: "Can I export the wellness report?",
      answer: "Yes, CSV export ships with 2.4.0.",
      scope: "product",
      published: true,
    },
  ],
  approval: { status: "applied", approver: "Arjun Mehta", at: "2026-08-02T10:00:00Z" },
  savedAgoSeconds: 12,
};

export const COUPONS: CouponRow[] = [
  {
    id: "cp-1",
    code: "LAUNCH10",
    kind: "percent",
    valueBps: 1000,
    startsAt: "2026-09-01",
    endsAt: "2026-10-31",
    used: 12,
    max: 50,
    products: [],
    firstPurchaseOnly: false,
    state: "active",
    createdBy: "Priya",
  },
  {
    id: "cp-2",
    code: "WELCOME500",
    kind: "fixed",
    amount: inr(50000),
    startsAt: "2026-09-15",
    used: 3,
    products: [],
    firstPurchaseOnly: true,
    state: "active",
    createdBy: "Arjun",
  },
  {
    id: "cp-3",
    code: "DIWALI25",
    kind: "percent",
    valueBps: 2500,
    startsAt: "2026-10-20",
    endsAt: "2026-11-05",
    used: 0,
    max: 100,
    products: ["FitDesk Pro", "TradeFlow"],
    firstPurchaseOnly: false,
    state: "scheduled",
    createdBy: "Priya",
  },
  {
    id: "cp-4",
    code: "BETA50",
    kind: "percent",
    valueBps: 5000,
    startsAt: "2026-03-01",
    endsAt: "2026-06-30",
    used: 20,
    max: 20,
    products: ["ShopSync"],
    firstPurchaseOnly: false,
    state: "exhausted",
    createdBy: "Arjun",
  },
  {
    id: "cp-5",
    code: "SUMMER15",
    kind: "percent",
    valueBps: 1500,
    startsAt: "2026-05-01",
    endsAt: "2026-07-31",
    used: 8,
    max: 200,
    products: [],
    firstPurchaseOnly: false,
    state: "expired",
    createdBy: "Priya",
  },
  {
    id: "cp-6",
    code: "PARTNER1000",
    kind: "fixed",
    amount: inr(100000),
    startsAt: "2026-08-01",
    used: 1,
    products: ["TradeFlow"],
    firstPurchaseOnly: false,
    state: "inactive",
    createdBy: "Arjun",
  },
];

/* ----------------------------------------------------------------- commerce */

export const APPROVALS: ApprovalItem[] = [
  {
    id: "apr-1",
    type: "product.publish",
    subject: "MIS Portal",
    subjectHref: href("/products"),
    requestedBy: ARJUN,
    requestedAt: "2026-09-25T07:05:00Z",
    comment: "Ready for launch with the implementation offering; publish on 1 Oct.",
    status: "pending",
    diff: [
      {
        label: "Offering with base price + method",
        after: "Implementation · ₹1,20,000.00 · Bank transfer ✔",
      },
      { label: "Images", after: "3 images with alt text ✔" },
      { label: "Ownership", after: "v1 active · Company 30 % · Priya 35 % · Arjun 35 % ✔" },
      { label: "SEO title", after: "Set (54 chars) ✔" },
      { label: "Publish at", after: "01 Oct 2026, 09:00 IST" },
    ],
  },
  {
    id: "apr-2",
    type: "ownership.change",
    subject: "TradeFlow · ownership v3",
    subjectHref: href("/products"),
    requestedBy: ARJUN,
    requestedAt: "2026-09-24T13:20:00Z",
    comment: "Rebalancing after Priya took over support.",
    status: "pending",
    diff: [
      { label: "Company cut", before: "20.00 %", after: "20.00 %" },
      { label: "Priya Nair", before: "40.00 %", after: "50.00 %" },
      { label: "Arjun Mehta", before: "40.00 %", after: "30.00 %" },
      { label: "Effective from", before: "01 Mar 2026", after: "01 Oct 2026" },
    ],
  },
  {
    id: "apr-3",
    type: "project_order.split",
    subject: "CK-ORD-000015 · Global Textiles portal",
    subjectHref: href("/orders"),
    requestedBy: ARJUN,
    requestedAt: "2026-09-23T10:00:00Z",
    comment: "Client invoice for phase 1. Split per our project agreement.",
    status: "pending",
    note: "Invoice and payment are blocked until approved.",
    diff: [
      {
        label: "Line 1 · Discovery workshop (₹80,000.00)",
        after: "Company 20 % · Priya 40 % · Arjun 40 %",
      },
      {
        label: "Line 2 · Portal build phase 1 (₹3,20,000.00)",
        after: "Company 20 % · Priya 30 % · Arjun 50 %",
      },
      { label: "Order total", after: "₹4,00,000.00 + tax" },
    ],
  },
  {
    id: "apr-4",
    type: "refund.issue",
    subject: "CK-ORD-000007 · Meera Shah",
    subjectHref: href("/orders"),
    requestedBy: PRIYA,
    requestedAt: "2026-09-22T15:45:00Z",
    comment: "Customer bought Starter twice by mistake; refunding the second one.",
    status: "pending",
    diff: [
      { label: "Payment", after: "UPI · ₹999.00 · confirmed 20 Sep" },
      { label: "Refund amount", after: "₹999.00 (full)" },
      { label: "Revoke entitlements", after: "Yes" },
      { label: "Refundability", after: "Product is refundable ✔" },
    ],
  },
  {
    id: "apr-5",
    type: "payout.record",
    subject: "Payout to Arjun Mehta",
    subjectHref: href("/finance/partners"),
    requestedBy: PRIYA,
    requestedAt: "2026-09-23T14:00:00Z",
    comment: "September payout, transferred by NEFT.",
    status: "applied",
    appliedAt: "2026-09-23T14:30:00Z",
    decision: {
      by: "Arjun Mehta",
      at: "2026-09-23T14:29:00Z",
      decision: "approve",
      comment: "Received, thanks.",
    },
    diff: [
      { label: "Amount", after: "₹42,000.00" },
      { label: "Paid on", after: "23 Sep 2026" },
      { label: "Reference", after: "NEFT N268261234567" },
      { label: "Available balance", before: "₹61,240.00", after: "₹19,240.00" },
    ],
  },
  {
    id: "apr-6",
    type: "product.archive",
    subject: "OldCRM",
    subjectHref: href("/products"),
    requestedBy: ARJUN,
    requestedAt: "2026-06-01T08:00:00Z",
    comment: "Sunset; 58 orders so archive, not delete.",
    status: "applied",
    appliedAt: "2026-06-01T12:00:00Z",
    decision: { by: "Priya Nair", at: "2026-06-01T11:58:00Z", decision: "approve" },
    diff: [{ label: "Orders", after: "58 — existing customers keep access" }],
  },
  {
    id: "apr-7",
    type: "admin.user_change",
    subject: "Invite sam@codekraft.in as Admin",
    subjectHref: href("/admin-users"),
    requestedBy: PRIYA,
    requestedAt: "2026-09-10T09:00:00Z",
    comment: "Contractor for content.",
    status: "rejected",
    decision: {
      by: "Arjun Mehta",
      at: "2026-09-10T16:00:00Z",
      decision: "reject",
      comment: "Let's wait until the content workflow is stable.",
    },
    diff: [
      { label: "Role", before: "—", after: "Admin" },
      { label: "Partner", after: "No" },
    ],
  },
  {
    id: "apr-8",
    type: "ledger.adjustment",
    subject: "Adjustment · bank shortfall write-off",
    subjectHref: href("/finance/adjustments"),
    requestedBy: ARJUN,
    requestedAt: "2026-09-24T09:15:00Z",
    comment: "Write off ₹40 shortfall on CK-ORD-000009 as bank charge.",
    status: "pending",
    diff: [
      { label: "Bank · bank charge", after: "−₹40.00" },
      { label: "Company · balancing", after: "+₹40.00" },
    ],
  },
];

export const ORDERS: OrderRow[] = [
  {
    id: "o-12",
    number: "CK-ORD-000012",
    placedAt: "2026-09-24T14:02:00Z",
    customer: { id: "cust-1", name: "Ravi Kumar", email: "ravi@example.com" },
    type: "product",
    items: ["FitDesk Pro · Team"],
    total: inr(1179882),
    payment: { provider: "manual_upi", status: "submitted", reference: "UTR 4271xx9921" },
    status: "pending_payment",
    expiresAt: "2026-10-01T14:02:00Z",
    awaitingConfirmation: true,
  },
  {
    id: "o-14",
    number: "CK-ORD-000014",
    placedAt: "2026-09-23T09:10:00Z",
    customer: { id: "cust-3", name: "Global Textiles", email: "accounts@globaltextiles.in" },
    type: "product",
    items: ["TradeFlow · Single site"],
    total: inr(2949882),
    payment: { provider: "manual_bank", status: "submitted", reference: "NEFT N2681…" },
    status: "pending_payment",
    expiresAt: "2026-09-30T09:10:00Z",
    awaitingConfirmation: true,
  },
  {
    id: "o-13",
    number: "CK-ORD-000013",
    placedAt: "2026-09-23T18:30:00Z",
    customer: { id: "cust-4", name: "Dev Sharma", email: "dev@acme.example" },
    type: "product",
    items: ["Brand Kit Templates"],
    total: inr(29900),
    payment: { provider: "manual_upi", status: "initiated" },
    status: "pending_payment",
    expiresAt: "2026-09-25T18:30:00Z",
    awaitingConfirmation: true,
  },
  {
    id: "o-15",
    number: "CK-ORD-000015",
    placedAt: "2026-09-23T10:00:00Z",
    customer: { id: "cust-3", name: "Global Textiles", email: "accounts@globaltextiles.in" },
    type: "project",
    items: ["Discovery workshop", "Portal build phase 1"],
    total: inr(47200000),
    payment: { provider: "manual_bank", status: "initiated" },
    status: "pending_payment",
    awaitingConfirmation: false,
  },
  {
    id: "o-9",
    number: "CK-ORD-000009",
    placedAt: "2026-09-20T11:00:00Z",
    customer: { id: "cust-3", name: "Global Textiles", email: "accounts@globaltextiles.in" },
    type: "product",
    items: ["TradeFlow · Single site"],
    total: inr(2949882),
    payment: { provider: "manual_bank", status: "confirmed", reference: "NEFT N268209876" },
    status: "paid",
    invoiceNumber: "CK/2026-27/0006",
    awaitingConfirmation: false,
  },
  {
    id: "o-7",
    number: "CK-ORD-000007",
    placedAt: "2026-09-19T08:15:00Z",
    customer: { id: "cust-2", name: "Meera Shah", email: "meera@shahdesigns.in" },
    type: "product",
    items: ["FitDesk Pro · Starter"],
    total: inr(117882),
    payment: { provider: "manual_upi", status: "confirmed", reference: "UTR 4270118834" },
    status: "fulfilled",
    invoiceNumber: "CK/2026-27/0005",
    awaitingConfirmation: false,
  },
  {
    id: "o-5",
    number: "CK-ORD-000005",
    placedAt: "2026-09-10T13:40:00Z",
    customer: { id: "cust-5", name: "Nimbus Retail", email: "it@nimbusretail.com" },
    type: "product",
    items: ["ShopSync · Pro", "+1"],
    total: inr(353764),
    payment: { provider: "manual_bank", status: "refunded", reference: "NEFT N2679…" },
    status: "refunded",
    invoiceNumber: "CK/2026-27/0003",
    awaitingConfirmation: false,
  },
  {
    id: "o-4",
    number: "CK-ORD-000004",
    placedAt: "2026-09-08T16:00:00Z",
    customer: { id: "cust-4", name: "Dev Sharma", email: "dev@acme.example" },
    type: "product",
    items: ["TradeFlow · Single site"],
    total: inr(2949882),
    payment: { provider: "manual_upi", status: "failed" },
    status: "failed",
    awaitingConfirmation: false,
  },
  {
    id: "o-3",
    number: "CK-ORD-000003",
    placedAt: "2026-09-02T10:00:00Z",
    customer: { id: "cust-6", name: "Lena Fischer", email: "lena@fischer.de" },
    type: "product",
    items: ["FitDesk Pro · Team"],
    total: usd(14900),
    payment: { provider: "manual_bank", status: "confirmed", reference: "SWIFT 0091…" },
    status: "fulfilled",
    invoiceNumber: "CK/2026-27/0002",
    awaitingConfirmation: false,
  },
  {
    id: "o-2",
    number: "CK-ORD-000002",
    placedAt: "2026-08-28T09:00:00Z",
    customer: { id: "cust-2", name: "Meera Shah", email: "meera@shahdesigns.in" },
    type: "product",
    items: ["Brand Kit Templates"],
    total: inr(29900),
    payment: { provider: "manual_upi", status: "confirmed", reference: "UTR 4269…" },
    status: "cancelled",
    awaitingConfirmation: false,
  },
];

export const ORDER_DETAIL: OrderDetailData = {
  order: ORDERS[0] as OrderRow,
  payment: {
    provider: "manual_upi",
    status: "submitted",
    due: inr(1179882),
    customerReference: "UTR 427109921184",
    submittedAt: "2026-09-25T08:52:00Z",
    instructionsSnapshot: "UPI · codekraft@icici · CodeKraft",
    previousFailed: [{ at: "2026-09-24T14:40:00Z", reason: "Customer entered an invalid UTR" }],
  },
  items: [
    {
      id: "oi-1",
      product: "FitDesk Pro",
      offering: "Team (annual)",
      qty: 1,
      unit: inr(999900),
      discount: inr(0),
      tax: inr(179982),
      total: inr(1179882),
      ownershipVersion: "v2",
      deliveryType: "saas",
      entitlement: { status: "pending", provisioning: "pending", accessEnds: "2027-09-25" },
    },
  ],
  ledger: [],
  timeline: [
    {
      at: "2026-09-24T14:02:00Z",
      actor: "Ravi Kumar",
      text: "Order placed · UPI instructions shown",
      kind: "customer",
    },
    {
      at: "2026-09-24T14:40:00Z",
      actor: "System",
      text: "Reference rejected (invalid UTR format)",
      kind: "system",
    },
    {
      at: "2026-09-25T08:52:00Z",
      actor: "Ravi Kumar",
      text: "Reference submitted · UTR 427109921184",
      kind: "customer",
    },
  ],
  customer: {
    id: "cust-1",
    name: "Ravi Kumar",
    email: "ravi@example.com",
    country: "IN",
    company: "Kumar Consulting",
    gstin: "27AAPFU0939F1ZV",
    tags: ["vip", "b2b"],
    notes: "Prefers UPI. Asked about a 40-seat rollout — see lead.",
  },
  billing: { name: "Kumar Consulting LLP", address: "14 MG Road, Pune 411001", country: "IN" },
  coupon: { code: "LAUNCH10", discount: inr(0) },
  refunds: [],
  refundable: true,
  linkedQueries: [
    { id: "q-3", subject: "Can I pay from a company account?", status: "waiting_customer" },
  ],
};

export const ORDER_DETAIL_PAID: OrderDetailData = {
  ...ORDER_DETAIL,
  order: ORDERS[4] as OrderRow,
  payment: {
    provider: "manual_bank",
    status: "confirmed",
    due: inr(2949882),
    customerReference: "NEFT N268209876",
    submittedAt: "2026-09-20T12:10:00Z",
    instructionsSnapshot: "Bank · ICICI · A/c 0012 3456 7890 · IFSC ICIC0000012",
    received: inr(2949842),
    shortfall: inr(4000),
    confirmedBy: "Priya Nair",
    confirmedAt: "2026-09-20T15:02:00Z",
    previousFailed: [],
  },
  items: [
    {
      id: "oi-2",
      product: "TradeFlow",
      offering: "Single site",
      qty: 1,
      unit: inr(2499900),
      discount: inr(0),
      tax: inr(449982),
      total: inr(2949882),
      ownershipVersion: "v2",
      deliveryType: "download",
      entitlement: {
        status: "active",
        downloadsUsed: 2,
        downloadCap: 5,
        keyIssued: true,
        provisioning: "n/a",
      },
    },
  ],
  ledger: [
    {
      seq: 1071,
      at: "2026-09-20T15:02:00Z",
      type: "sale",
      party: "Company",
      partyType: "company",
      order: "CK-ORD-000009",
      amount: inr(2499900),
      amountInr: 2499900,
      memo: "TradeFlow · Single site",
      ref: "pay-9",
      createdBy: "System",
    },
    {
      seq: 1072,
      at: "2026-09-20T15:02:00Z",
      type: "tax_collected",
      party: "Tax authority",
      partyType: "tax_authority",
      order: "CK-ORD-000009",
      amount: inr(449982),
      amountInr: 449982,
      memo: "GST 18 %",
      ref: "pay-9",
      createdBy: "System",
    },
    {
      seq: 1073,
      at: "2026-09-20T15:02:00Z",
      type: "bank_charge",
      party: "Bank",
      partyType: "bank",
      order: "CK-ORD-000009",
      amount: inr(-4000),
      amountInr: -4000,
      memo: "Shortfall on receipt",
      ref: "pay-9",
      createdBy: "System",
    },
    {
      seq: 1074,
      at: "2026-09-20T15:02:00Z",
      type: "company_cut",
      party: "Company",
      partyType: "company",
      order: "CK-ORD-000009",
      amount: inr(499180),
      amountInr: 499180,
      memo: "20 % of distributable",
      ref: "pay-9",
      createdBy: "System",
    },
    {
      seq: 1075,
      at: "2026-09-20T15:02:00Z",
      type: "partner_allocation",
      party: "Priya Nair",
      partyType: "partner",
      order: "CK-ORD-000009",
      amount: inr(998360),
      amountInr: 998360,
      memo: "40 % of distributable",
      ref: "pay-9",
      createdBy: "System",
    },
    {
      seq: 1076,
      at: "2026-09-20T15:02:00Z",
      type: "partner_allocation",
      party: "Arjun Mehta",
      partyType: "partner",
      order: "CK-ORD-000009",
      amount: inr(998360),
      amountInr: 998360,
      memo: "40 % of distributable",
      ref: "pay-9",
      createdBy: "System",
    },
  ],
  allocation: {
    companyCut: inr(499180),
    lines: [
      { partner: "Priya Nair", amount: inr(998360), bps: 4000 },
      { partner: "Arjun Mehta", amount: inr(998360), bps: 4000 },
    ],
  },
  timeline: [
    {
      at: "2026-09-20T11:00:00Z",
      actor: "Global Textiles",
      text: "Order placed · bank instructions emailed",
      kind: "customer",
    },
    {
      at: "2026-09-20T12:10:00Z",
      actor: "Global Textiles",
      text: "Reference submitted · NEFT N268209876",
      kind: "customer",
    },
    {
      at: "2026-09-20T15:02:00Z",
      actor: "Priya Nair",
      text: "Payment confirmed · ₹40.00 shortfall recorded as bank charge",
      kind: "admin",
    },
    {
      at: "2026-09-20T15:02:00Z",
      actor: "System",
      text: "Invoice CK/2026-27/0006 issued · ledger posted (seq 1071–1076)",
      kind: "system",
    },
    {
      at: "2026-09-20T15:02:00Z",
      actor: "System",
      text: "Entitlement active · 5 downloads",
      kind: "system",
    },
  ],
  customer: {
    id: "cust-3",
    name: "Global Textiles",
    email: "accounts@globaltextiles.in",
    country: "IN",
    company: "Global Textiles Pvt Ltd",
    gstin: "24AABCG1234H1Z5",
    tags: ["b2b"],
    notes: "Accounts team pays by NEFT on Mondays.",
  },
  billing: {
    name: "Global Textiles Pvt Ltd",
    address: "Plot 9, GIDC, Surat 395010",
    country: "IN",
  },
  coupon: undefined,
  linkedQueries: [],
};

export const CUSTOMER_OPTIONS = [
  { id: "cust-1", name: "Ravi Kumar", email: "ravi@example.com" },
  { id: "cust-2", name: "Meera Shah", email: "meera@shahdesigns.in" },
  { id: "cust-3", name: "Global Textiles", email: "accounts@globaltextiles.in" },
  { id: "cust-4", name: "Dev Sharma", email: "dev@acme.example" },
];

export const OFFERING_OPTIONS: OfferingOption[] = [
  { id: "off-1", label: "FitDesk Pro · Starter (monthly)", price: inr(99900), oneTime: false },
  { id: "off-2", label: "FitDesk Pro · Team (annual)", price: inr(999900), oneTime: false },
  {
    id: "off-4",
    label: "TradeFlow · Single site",
    price: inr(2499900),
    oneTime: true,
    owned: true,
  },
  { id: "off-5", label: "Brand Kit Templates", price: inr(29900), oneTime: true },
  { id: "off-6", label: "InvoiceKit · Lifetime", price: inr(499900), oneTime: true },
];

export const QUOTES: QuoteRow[] = [
  {
    id: "qt-1",
    title: "FitDesk Pro · 40-seat rollout",
    customer: CUSTOMER_OPTIONS[0] as QuoteRow["customer"],
    offering: "FitDesk Pro · Enterprise rollout",
    amount: inr(18000000),
    taxApplies: true,
    expiresAt: "2026-10-08",
    status: "sent",
    sentAt: "2026-09-24T10:00:00Z",
    description: "40 seats for 12 months, onboarding workshop, SSO setup.",
    internalNote: "Came from lead Acme Ltd.",
    payLink: "https://codekraft.example/quote/8f3k…",
    timeline: [
      { at: "2026-09-23T16:00:00Z", actor: "Priya Nair", text: "Created" },
      { at: "2026-09-24T10:00:00Z", actor: "Priya Nair", text: "Sent to ravi@example.com" },
      { at: "2026-09-24T18:22:00Z", actor: "Ravi Kumar", text: "Viewed" },
    ],
  },
  {
    id: "qt-2",
    title: "TradeFlow · multi-site licence",
    customer: CUSTOMER_OPTIONS[2] as QuoteRow["customer"],
    amount: inr(6500000),
    taxApplies: true,
    expiresAt: "2026-09-30",
    status: "accepted",
    sentAt: "2026-09-15T09:00:00Z",
    orderNumber: "CK-ORD-000011",
    payLink: "https://codekraft.example/quote/a91x…",
    timeline: [],
  },
  {
    id: "qt-3",
    title: "ShopSync · custom connector",
    customer: CUSTOMER_OPTIONS[3] as QuoteRow["customer"],
    amount: inr(4500000),
    taxApplies: false,
    expiresAt: "2026-10-15",
    status: "draft",
    payLink: "—",
    timeline: [],
  },
  {
    id: "qt-4",
    title: "MIS Portal · phase 2",
    customer: CUSTOMER_OPTIONS[2] as QuoteRow["customer"],
    amount: inr(28000000),
    taxApplies: true,
    expiresAt: "2026-08-31",
    status: "expired",
    sentAt: "2026-08-10T09:00:00Z",
    payLink: "https://codekraft.example/quote/z10q…",
    timeline: [],
  },
  {
    id: "qt-5",
    title: "Brand Kit · agency bundle",
    customer: CUSTOMER_OPTIONS[1] as QuoteRow["customer"],
    amount: inr(120000),
    taxApplies: false,
    expiresAt: "2026-09-20",
    status: "paid",
    sentAt: "2026-09-05T09:00:00Z",
    orderNumber: "CK-ORD-000008",
    payLink: "https://codekraft.example/quote/pp7…",
    timeline: [],
  },
];

export const CUSTOMERS: CustomerRow[] = [
  {
    id: "cust-1",
    name: "Ravi Kumar",
    email: "ravi@example.com",
    verified: true,
    company: "Kumar Consulting",
    country: "IN",
    tags: ["vip", "b2b"],
    activeEntitlements: 2,
    lifetimeSpendInr: 1297764,
    openOrders: 1,
    openQueries: 1,
    status: "active",
    joinedAt: "2026-05-12T10:00:00Z",
    lastSeenAt: "2026-09-25T08:52:00Z",
  },
  {
    id: "cust-2",
    name: "Meera Shah",
    email: "meera@shahdesigns.in",
    verified: true,
    company: "Shah Designs",
    country: "IN",
    tags: ["designer"],
    activeEntitlements: 3,
    lifetimeSpendInr: 267682,
    openOrders: 0,
    openQueries: 1,
    status: "active",
    joinedAt: "2026-06-02T10:00:00Z",
    lastSeenAt: "2026-09-24T18:05:00Z",
  },
  {
    id: "cust-3",
    name: "Global Textiles",
    email: "accounts@globaltextiles.in",
    verified: true,
    company: "Global Textiles Pvt Ltd",
    country: "IN",
    tags: ["b2b", "project"],
    activeEntitlements: 1,
    lifetimeSpendInr: 9449882,
    openOrders: 2,
    openQueries: 0,
    status: "active",
    joinedAt: "2026-07-20T10:00:00Z",
    lastSeenAt: "2026-09-23T09:10:00Z",
  },
  {
    id: "cust-4",
    name: "Dev Sharma",
    email: "dev@acme.example",
    verified: false,
    company: "Acme Ltd",
    country: "IN",
    tags: [],
    activeEntitlements: 0,
    lifetimeSpendInr: 0,
    openOrders: 1,
    openQueries: 0,
    status: "active",
    joinedAt: "2026-09-08T10:00:00Z",
    lastSeenAt: "2026-09-23T18:30:00Z",
  },
  {
    id: "cust-5",
    name: "Nimbus Retail",
    email: "it@nimbusretail.com",
    verified: true,
    company: "Nimbus Retail",
    country: "IN",
    tags: ["chargeback"],
    activeEntitlements: 0,
    lifetimeSpendInr: 353764,
    openOrders: 0,
    openQueries: 0,
    status: "suspended",
    joinedAt: "2026-08-01T10:00:00Z",
    lastSeenAt: "2026-09-12T10:00:00Z",
  },
  {
    id: "cust-6",
    name: "Lena Fischer",
    email: "lena@fischer.de",
    verified: true,
    country: "DE",
    tags: ["eu"],
    activeEntitlements: 1,
    lifetimeSpendInr: 1245200,
    openOrders: 0,
    openQueries: 0,
    status: "active",
    joinedAt: "2026-08-30T10:00:00Z",
    lastSeenAt: "2026-09-20T10:00:00Z",
  },
  {
    id: "cust-7",
    name: "Deleted customer",
    email: "deleted-7@anon.invalid",
    verified: false,
    country: "—",
    tags: [],
    activeEntitlements: 0,
    lifetimeSpendInr: 79900,
    openOrders: 0,
    openQueries: 0,
    status: "deleted",
    joinedAt: "2026-04-01T10:00:00Z",
    anonymisedAt: "2026-09-01T10:00:00Z",
  },
];

export const ENTITLEMENTS: EntitlementRow[] = [
  {
    id: "ent-1",
    customer: CUSTOMER_OPTIONS[0] as EntitlementRow["customer"],
    product: "FitDesk Pro",
    offering: "Team (annual)",
    type: "saas",
    status: "active",
    accessEnds: "2027-09-25",
    subscription: { interval: "annual", periodEnd: "2027-09-25", status: "active" },
    provisioning: "pending",
    orderNumber: "CK-ORD-000012",
    orderId: "o-12",
  },
  {
    id: "ent-2",
    customer: CUSTOMER_OPTIONS[2] as EntitlementRow["customer"],
    product: "TradeFlow",
    offering: "Single site",
    type: "download",
    status: "active",
    downloadsUsed: 2,
    downloadCap: 5,
    keyIssued: true,
    provisioning: "n/a",
    orderNumber: "CK-ORD-000009",
    orderId: "o-9",
  },
  {
    id: "ent-3",
    customer: CUSTOMER_OPTIONS[1] as EntitlementRow["customer"],
    product: "TradeFlow",
    offering: "Single site",
    type: "download",
    status: "active",
    downloadsUsed: 5,
    downloadCap: 5,
    keyIssued: true,
    provisioning: "n/a",
    orderNumber: "CK-ORD-000006",
    orderId: "o-6",
  },
  {
    id: "ent-4",
    customer: CUSTOMER_OPTIONS[1] as EntitlementRow["customer"],
    product: "FitDesk Pro",
    offering: "Starter (monthly)",
    type: "saas",
    status: "active",
    subscription: { interval: "monthly", periodEnd: "2026-10-19", status: "past_due" },
    provisioning: "done",
    orderNumber: "CK-ORD-000007",
    orderId: "o-7",
  },
  {
    id: "ent-5",
    customer: { id: "cust-5", name: "Nimbus Retail", email: "it@nimbusretail.com" },
    product: "ShopSync",
    offering: "Pro",
    type: "hosted",
    status: "revoked",
    provisioning: "done",
    orderNumber: "CK-ORD-000005",
    orderId: "o-5",
  },
  {
    id: "ent-6",
    customer: { id: "cust-6", name: "Lena Fischer", email: "lena@fischer.de" },
    product: "FitDesk Pro",
    offering: "Team (annual)",
    type: "saas",
    status: "active",
    accessEnds: "2027-09-02",
    subscription: { interval: "annual", periodEnd: "2027-09-02", status: "active" },
    provisioning: "done",
    orderNumber: "CK-ORD-000003",
    orderId: "o-3",
  },
  {
    id: "ent-7",
    customer: CUSTOMER_OPTIONS[3] as EntitlementRow["customer"],
    product: "InvoiceKit",
    offering: "Lifetime",
    type: "license",
    status: "pending",
    keyIssued: false,
    provisioning: "n/a",
    orderNumber: "—",
    orderId: "",
    grantedManually: true,
  },
  {
    id: "ent-8",
    customer: CUSTOMER_OPTIONS[0] as EntitlementRow["customer"],
    product: "OldCRM",
    offering: "Basic",
    type: "saas",
    status: "expired",
    accessEnds: "2026-09-01",
    provisioning: "done",
    orderNumber: "CK-ORD-000001",
    orderId: "o-1",
  },
];

export const DELIVERY_TASKS: DeliveryTaskRow[] = [
  {
    id: "dt-1",
    createdAt: "2026-09-23T09:00:00Z",
    kind: "provision",
    customer: CUSTOMER_OPTIONS[0] as DeliveryTaskRow["customer"],
    product: "FitDesk Pro",
    offering: "Team (annual)",
    entitlementStatus: "active",
    assignedTo: "Priya Nair",
    status: "open",
    orderId: "o-12",
    orderNumber: "CK-ORD-000012",
    hints:
      "Create the workspace at app.fitdesk.example/admin, invite ravi@example.com as owner, tick credentials sent.",
  },
  {
    id: "dt-2",
    createdAt: "2026-09-22T11:30:00Z",
    kind: "revoke_external",
    customer: { id: "cust-5", name: "Nimbus Retail", email: "it@nimbusretail.com" },
    product: "ShopSync",
    offering: "Pro",
    entitlementStatus: "revoked",
    status: "open",
    orderId: "o-5",
    orderNumber: "CK-ORD-000005",
    note: "Refund approved — disable hosted tenant nimbus.shopsync.example.",
    hints: "Revoke access in ShopSync for it@nimbusretail.com, then mark done.",
  },
  {
    id: "dt-3",
    createdAt: "2026-09-24T16:00:00Z",
    kind: "provision",
    customer: { id: "cust-6", name: "Lena Fischer", email: "lena@fischer.de" },
    product: "FitDesk Pro",
    offering: "Team (annual)",
    entitlementStatus: "active",
    assignedTo: "Arjun Mehta",
    status: "open",
    orderId: "o-3",
    orderNumber: "CK-ORD-000003",
  },
  {
    id: "dt-4",
    createdAt: "2026-09-10T10:00:00Z",
    kind: "provision",
    customer: CUSTOMER_OPTIONS[1] as DeliveryTaskRow["customer"],
    product: "FitDesk Pro",
    offering: "Starter (monthly)",
    entitlementStatus: "active",
    assignedTo: "Priya Nair",
    status: "done",
    orderId: "o-7",
    orderNumber: "CK-ORD-000007",
    note: "Workspace created, credentials sent 10 Sep.",
  },
];

export const QUERIES: QueryRow[] = [
  {
    id: "q-1",
    subject: "Download cap reached — can you reset?",
    customer: CUSTOMER_OPTIONS[1],
    source: "dashboard",
    status: "open",
    snippet: "I re-downloaded after a laptop swap and now it says 5/5…",
    updatedAt: "2026-09-24T18:05:00Z",
    unread: true,
    related: [
      { kind: "entitlement", label: "TradeFlow · Single site" },
      { kind: "order", label: "CK-ORD-000006", href: href("/orders") },
    ],
  },
  {
    id: "q-2",
    subject: "Refund request · duplicate Starter purchase",
    customer: CUSTOMER_OPTIONS[1],
    source: "order",
    status: "open",
    snippet: "I bought Starter twice on the same day by mistake.",
    updatedAt: "2026-09-22T15:00:00Z",
    assignee: PRIYA,
    unread: false,
    related: [{ kind: "order", label: "CK-ORD-000007", href: href("/orders") }],
    refundRequest: { order: "CK-ORD-000007", method: "UPI", amount: inr(117882), refundable: true },
  },
  {
    id: "q-3",
    subject: "Can I pay from a company account?",
    customer: CUSTOMER_OPTIONS[0],
    source: "chatbot",
    status: "waiting_customer",
    snippet: "Assistant escalated: customer asked about GST invoices for a company card.",
    updatedAt: "2026-09-24T12:00:00Z",
    assignee: ARJUN,
    unread: false,
    related: [
      { kind: "conversation", label: "Conversation 4f21" },
      { kind: "order", label: "CK-ORD-000012", href: href("/orders") },
    ],
  },
  {
    id: "q-4",
    subject: "Does TradeFlow support multi-currency?",
    visitorEmail: "sam@finops.example",
    source: "form",
    status: "open",
    snippet: "We operate in INR and USD…",
    updatedAt: "2026-09-23T10:00:00Z",
    unread: true,
    related: [{ kind: "product", label: "TradeFlow", href: href("/products") }],
  },
  {
    id: "q-5",
    subject: "Invoice shows wrong GSTIN",
    customer: CUSTOMER_OPTIONS[2],
    source: "email",
    status: "resolved",
    snippet: "Logged from accounts@ email: GSTIN on CK/2026-27/0006 has a typo.",
    updatedAt: "2026-09-21T09:30:00Z",
    assignee: PRIYA,
    unread: false,
    related: [{ kind: "order", label: "CK-ORD-000009", href: href("/orders") }],
  },
  {
    id: "q-6",
    subject: "Rollout timeline for 40 seats",
    customer: CUSTOMER_OPTIONS[0],
    source: "manual",
    status: "closed",
    snippet: "Discussed on call; moved to lead.",
    updatedAt: "2026-09-18T09:30:00Z",
    assignee: ARJUN,
    unread: false,
    related: [{ kind: "lead", label: "Acme Ltd", href: href("/leads") }],
  },
];

export const QUERY_THREAD: QueryThread = {
  query: QUERIES[1] as QueryRow,
  messages: [
    {
      id: "m1",
      authorKind: "system",
      author: "System",
      at: "2026-09-22T14:58:00Z",
      text: "Refund request from the order page · CK-ORD-000007 · UPI · ₹1,178.82 · FitDesk Pro is refundable.",
    },
    {
      id: "m2",
      authorKind: "customer",
      author: "Meera Shah",
      at: "2026-09-22T15:00:00Z",
      text: "I bought Starter twice on the same day by mistake. Could you refund the second one? UTR 4270118834.",
    },
    {
      id: "m3",
      authorKind: "admin",
      author: "Priya Nair",
      at: "2026-09-22T15:40:00Z",
      text: "Checked both payments — the second confirmation came from a retried checkout. Proposing a full refund; Arjun needs to approve it.",
      internal: true,
    },
    {
      id: "m4",
      authorKind: "admin",
      author: "Priya Nair",
      at: "2026-09-22T15:45:00Z",
      text: "Hi Meera, sorry about that. I have raised a full refund of ₹1,178.82 for the duplicate order; you will get an email once it is approved (usually within one business day).",
      attachments: ["refund-summary.pdf"],
    },
    {
      id: "m5",
      authorKind: "customer",
      author: "Meera Shah",
      at: "2026-09-23T08:10:00Z",
      text: "Thanks! Will the access for the first order stay active?",
    },
  ],
  snippets: [
    "We confirm payments manually within one business day.",
    "Refunds are reviewed by an admin; gateway payments are non-refundable.",
    "Your license key is available in Purchases & access on your dashboard.",
    "Could you share the UTR / transaction reference?",
    "Thanks for your patience — this is now resolved.",
  ],
};

export const LEADS: LeadRow[] = [
  {
    id: "ld-1",
    name: "Dev Sharma",
    company: "Acme Ltd",
    email: "dev@acme.example",
    phone: "+91 98xxx 11223",
    source: "product_cta",
    product: "FitDesk Pro",
    services: ["Implementation"],
    status: "new",
    priority: "high",
    createdAt: "2026-09-25T06:40:00Z",
  },
  {
    id: "ld-2",
    name: "Sam Iyer",
    company: "FinOps Labs",
    email: "sam@finops.example",
    source: "inquiry_form",
    services: ["Custom software", "Integrations"],
    status: "contacted",
    assignee: PRIYA,
    nextFollowUpAt: "2026-09-26T09:00:00Z",
    priority: "normal",
    createdAt: "2026-09-21T11:00:00Z",
  },
  {
    id: "ld-3",
    name: "Kavya R.",
    company: "Nimbus Retail",
    email: "kavya@nimbusretail.com",
    source: "chatbot",
    product: "ShopSync",
    services: ["Migration"],
    status: "qualified",
    assignee: ARJUN,
    nextFollowUpAt: "2026-09-22T09:00:00Z",
    priority: "high",
    createdAt: "2026-09-15T10:00:00Z",
  },
  {
    id: "ld-4",
    name: "Global Textiles",
    company: "Global Textiles Pvt Ltd",
    email: "accounts@globaltextiles.in",
    source: "manual",
    services: ["Portal build"],
    status: "proposal",
    assignee: ARJUN,
    nextFollowUpAt: "2026-09-29T09:00:00Z",
    priority: "high",
    createdAt: "2026-09-01T10:00:00Z",
  },
  {
    id: "ld-5",
    name: "Lena Fischer",
    email: "lena@fischer.de",
    source: "product_cta",
    product: "FitDesk Pro",
    services: [],
    status: "won",
    assignee: PRIYA,
    priority: "normal",
    createdAt: "2026-08-25T10:00:00Z",
    wonValue: usd(14900),
  },
  {
    id: "ld-6",
    name: "Tom Okafor",
    company: "Okafor Logistics",
    email: "tom@okafor.example",
    source: "inquiry_form",
    services: ["Custom software"],
    status: "lost",
    assignee: ARJUN,
    priority: "low",
    createdAt: "2026-08-10T10:00:00Z",
  },
  {
    id: "ld-7",
    name: "Anita Desai",
    company: "Desai & Co",
    email: "anita@desai.example",
    source: "inquiry_form",
    services: ["Integrations"],
    status: "new",
    priority: "normal",
    createdAt: "2026-09-24T15:00:00Z",
  },
  {
    id: "ld-8",
    name: "Rohit Verma",
    email: "rohit@verma.example",
    source: "chatbot",
    product: "TradeFlow",
    services: [],
    status: "contacted",
    assignee: PRIYA,
    nextFollowUpAt: "2026-09-25T08:00:00Z",
    priority: "normal",
    createdAt: "2026-09-20T09:00:00Z",
  },
];

export const LEAD_DETAIL: LeadDetailData = {
  lead: LEADS[2] as LeadRow,
  message:
    "We run three ShopSync stores on a legacy host and want to migrate to your hosted plan before Diwali. Need SSO and a data migration plan.",
  budgetHint: "₹3–5 lakh",
  submittedAt: "2026-09-15T10:00:00Z",
  turnstileVerified: true,
  ipCountry: "IN",
  activities: [
    {
      id: "a1",
      kind: "follow_up_set",
      actor: "Arjun Mehta",
      at: "2026-09-18T10:00:00Z",
      text: "Follow-up set for 22 Sep — send migration checklist",
    },
    {
      id: "a2",
      kind: "status_change",
      actor: "Arjun Mehta",
      at: "2026-09-17T14:00:00Z",
      text: "Contacted → Qualified",
    },
    {
      id: "a3",
      kind: "call",
      actor: "Arjun Mehta",
      at: "2026-09-17T13:30:00Z",
      text: "25-min call: 3 stores, ~40k SKUs, wants hosted + SSO. Decision by mid-October.",
    },
    {
      id: "a4",
      kind: "assignment",
      actor: "Arjun Mehta",
      at: "2026-09-15T11:00:00Z",
      text: "Claimed from pool",
    },
    {
      id: "a5",
      kind: "note",
      actor: "System",
      at: "2026-09-15T10:00:00Z",
      text: "Escalated from chatbot (conversation 7b2e)",
    },
  ],
  transcript: [
    { role: "user", text: "Can ShopSync migrate from Magento?" },
    {
      role: "assistant",
      text: "ShopSync imports products, orders and customers from Magento 2 via CSV or the REST API. For large catalogues we recommend a guided migration — would you like to talk to the team?",
    },
    { role: "user", text: "Yes, we have 3 stores." },
  ],
  followUpNote: "Send migration checklist and hosted pricing.",
  related: [
    { id: "ld-9", name: "Kavya R. (older)", status: "lost", createdAt: "2026-03-02T10:00:00Z" },
  ],
  admins: ADMINS,
};

export const CHATBOT: ChatbotMonitorData = {
  conversations: [
    {
      id: "4f21",
      startedAt: "2026-09-25T08:10:00Z",
      customer: "ravi@example.com",
      turns: 6,
      tokens: 3120,
      outcomes: ["escalated"],
      model: "claude-sonnet-4-5",
      promptVersion: "v4",
    },
    {
      id: "7b2e",
      startedAt: "2026-09-15T09:58:00Z",
      customer: "kavya@nimbusretail.com",
      turns: 8,
      tokens: 4410,
      outcomes: ["lead"],
      model: "claude-sonnet-4-5",
      promptVersion: "v3",
    },
    {
      id: "9c10",
      startedAt: "2026-09-24T19:30:00Z",
      turns: 3,
      tokens: 900,
      outcomes: ["fallback"],
      model: "claude-sonnet-4-5",
      promptVersion: "v4",
    },
    {
      id: "a0d3",
      startedAt: "2026-09-24T15:20:00Z",
      customer: "dev@acme.example",
      turns: 12,
      tokens: 7880,
      outcomes: ["cap"],
      model: "claude-sonnet-4-5",
      promptVersion: "v4",
    },
    {
      id: "b771",
      startedAt: "2026-09-23T11:00:00Z",
      turns: 4,
      tokens: 1500,
      outcomes: [],
      model: "claude-haiku-4-5",
      promptVersion: "v4",
    },
  ],
  transcript: {
    id: "4f21",
    turns: [
      { role: "system", text: "Prompt v4 · retrieval: 8 chunks" },
      { role: "user", text: "Can I pay from a company account and get a GST invoice?" },
      {
        role: "assistant",
        text: "Yes — pay by bank transfer or UPI from any account. Add your company name and GSTIN at checkout and the invoice will carry a GST breakdown once your payment is confirmed.",
        sources: ["FAQ: GST invoices", "Legal: Terms §4", "Product: FitDesk Pro › Pricing"],
        tokens: 412,
        latencyMs: 1830,
        stopReason: "end_turn",
      },
      { role: "menu", text: "Quick replies: Talk to a human · Track my order · Something else" },
      { role: "user", text: "Talk to a human" },
      {
        role: "assistant",
        text: "I have raised a query for the team with this conversation attached. They reply by email and in your dashboard.",
        tokens: 96,
        latencyMs: 640,
        stopReason: "end_turn",
      },
    ],
  },
  usage: {
    today: 1240,
    cap: 2000,
    usersAtCap: 3,
    perUserCap: 40,
    monthMessages: 28410,
    estimatedCostInr: 1842000,
    fallbackRate: 0.06,
    escalationRate: 0.11,
    daily: Array.from({ length: 30 }, (_, i) => ({
      label: `${i + 1}`,
      value: [900, 1100, 1300, 800, 1240, 1900, 2000, 1500][i % 8] as number,
    })),
    topUsers: [
      { email: "dev@acme.example", messages: 40, atCap: true },
      { email: "ravi@example.com", messages: 22, atCap: false },
      { email: "anon-7f21", messages: 40, atCap: true },
    ],
    models: [
      { label: "claude-sonnet-4-5", value: 1040 },
      { label: "claude-haiku-4-5", value: 200 },
    ],
  },
  prompts: [
    {
      version: "v4",
      name: "Grounded assistant",
      active: true,
      createdBy: "Priya Nair",
      createdAt: "2026-09-10T10:00:00Z",
      notes: "Adds refund-policy guardrail.",
      body: "You are the CodeKraft assistant. Answer only from the provided site content. Never quote contact details. If the user asks about refunds, explain that admins review refunds and gateway payments are non-refundable. Offer to escalate to a human when unsure.",
    },
    {
      version: "v3",
      name: "Grounded assistant",
      active: false,
      createdBy: "Arjun Mehta",
      createdAt: "2026-08-01T10:00:00Z",
      notes: "Lead capture flow.",
      body: "You are the CodeKraft assistant. Answer only from the provided site content. Offer to capture a lead when the user shows purchase intent.",
    },
    {
      version: "v2",
      name: "Menu-first",
      active: false,
      createdBy: "Priya Nair",
      createdAt: "2026-06-15T10:00:00Z",
      notes: "",
      body: "Start every conversation with the quick-reply menu.",
    },
  ],
  lastIndexRun: "2026-09-25T02:00:00Z",
  indexChunks: 412,
};

/* ------------------------------------------------------------------ finance */

export const LEDGER: LedgerEntry[] = (
  [
    ...ORDER_DETAIL_PAID.ledger,
    {
      seq: 1077,
      at: "2026-09-20T16:00:00Z",
      type: "sale",
      party: "Company",
      partyType: "company",
      order: "CK-ORD-000007",
      amount: inr(99900),
      amountInr: 99900,
      memo: "FitDesk Pro · Starter",
      ref: "pay-7",
      createdBy: "System",
    },
    {
      seq: 1078,
      at: "2026-09-20T16:00:00Z",
      type: "discount",
      party: "Customer",
      partyType: "customer",
      order: "CK-ORD-000007",
      amount: inr(-9990),
      amountInr: -9990,
      memo: "LAUNCH10",
      ref: "pay-7",
      createdBy: "System",
    },
    {
      seq: 1079,
      at: "2026-09-20T16:00:00Z",
      type: "tax_collected",
      party: "Tax authority",
      partyType: "tax_authority",
      order: "CK-ORD-000007",
      amount: inr(16184),
      amountInr: 16184,
      memo: "GST 18 %",
      ref: "pay-7",
      createdBy: "System",
    },
    {
      seq: 1080,
      at: "2026-09-20T16:00:00Z",
      type: "company_cut",
      party: "Company",
      partyType: "company",
      order: "CK-ORD-000007",
      amount: inr(17982),
      amountInr: 17982,
      memo: "20 %",
      ref: "pay-7",
      createdBy: "System",
    },
    {
      seq: 1081,
      at: "2026-09-20T16:00:00Z",
      type: "partner_allocation",
      party: "Priya Nair",
      partyType: "partner",
      order: "CK-ORD-000007",
      amount: inr(44955),
      amountInr: 44955,
      memo: "50 %",
      ref: "pay-7",
      createdBy: "System",
    },
    {
      seq: 1082,
      at: "2026-09-20T16:00:00Z",
      type: "partner_allocation",
      party: "Arjun Mehta",
      partyType: "partner",
      order: "CK-ORD-000007",
      amount: inr(26973),
      amountInr: 26973,
      memo: "30 %",
      ref: "pay-7",
      createdBy: "System",
    },
    {
      seq: 1083,
      at: "2026-09-21T10:00:00Z",
      type: "expense",
      party: "Company",
      partyType: "company",
      amount: inr(-1200000),
      amountInr: -1200000,
      memo: "Hosting · Hetzner · Sep",
      ref: "exp-31",
      createdBy: "Priya Nair",
    },
    {
      seq: 1084,
      at: "2026-09-22T10:00:00Z",
      type: "refund_sale",
      party: "Company",
      partyType: "company",
      order: "CK-ORD-000005",
      amount: inr(-299800),
      amountInr: -299800,
      memo: "Refund CN/2026-27/0001",
      ref: "ref-2",
      createdBy: "System",
    },
    {
      seq: 1085,
      at: "2026-09-22T10:00:00Z",
      type: "refund_partner_allocation",
      party: "Priya Nair",
      partyType: "partner",
      order: "CK-ORD-000005",
      amount: inr(-119920),
      amountInr: -119920,
      memo: "Reversal 40 %",
      ref: "ref-2",
      createdBy: "System",
    },
    {
      seq: 1086,
      at: "2026-09-22T10:00:00Z",
      type: "refund_partner_allocation",
      party: "Arjun Mehta",
      partyType: "partner",
      order: "CK-ORD-000005",
      amount: inr(-119920),
      amountInr: -119920,
      memo: "Reversal 40 %",
      ref: "ref-2",
      createdBy: "System",
    },
    {
      seq: 1087,
      at: "2026-09-02T12:00:00Z",
      type: "sale",
      party: "Company",
      partyType: "company",
      order: "CK-ORD-000003",
      amount: usd(14900),
      fxRate: "83.51000000",
      amountInr: 1244299,
      memo: "FitDesk Pro · Team (USD)",
      ref: "pay-3",
      createdBy: "System",
    },
    {
      seq: 1088,
      at: "2026-09-23T14:30:00Z",
      type: "payout",
      party: "Arjun Mehta",
      partyType: "partner",
      amount: inr(-4200000),
      amountInr: -4200000,
      memo: "NEFT N268261234567",
      ref: "apr-5",
      createdBy: "Priya Nair",
    },
    {
      seq: 1089,
      at: "2026-09-24T09:00:00Z",
      type: "adjustment",
      party: "Bank",
      partyType: "bank",
      order: "CK-ORD-000009",
      amount: inr(-4000),
      amountInr: -4000,
      memo: "Shortfall write-off (approved)",
      ref: "apr-8",
      createdBy: "Arjun Mehta",
    },
  ] as LedgerEntry[]
).sort((a, b) => b.seq - a.seq);

export const ALLOCATIONS: AllocationRow[] = [
  {
    id: "al-1",
    at: "2026-09-20T15:02:00Z",
    order: "CK-ORD-000009",
    item: "1",
    product: "TradeFlow",
    offering: "Single site",
    gross: inr(2499900),
    discount: inr(0),
    tax: inr(449982),
    gatewayFee: inr(0),
    bankCharge: inr(4000),
    distributable: inr(2495900),
    companyCut: { bps: 2000, amount: inr(499180) },
    partners: [
      { name: "Priya Nair", bps: 4000, amount: inr(998360) },
      { name: "Arjun Mehta", bps: 4000, amount: inr(998360) },
    ],
    ownershipVersion: "v2 · effective 1 Aug",
  },
  {
    id: "al-2",
    at: "2026-09-20T16:00:00Z",
    order: "CK-ORD-000007",
    item: "1",
    product: "FitDesk Pro",
    offering: "Starter",
    gross: inr(99900),
    discount: inr(9990),
    tax: inr(16184),
    gatewayFee: inr(0),
    bankCharge: inr(0),
    distributable: inr(89910),
    companyCut: { bps: 2000, amount: inr(17982) },
    partners: [
      { name: "Priya Nair", bps: 5000, amount: inr(44955) },
      { name: "Arjun Mehta", bps: 3000, amount: inr(26973) },
    ],
    ownershipVersion: "v2 · effective 1 Aug",
  },
  {
    id: "al-3",
    at: "2026-09-02T12:00:00Z",
    order: "CK-ORD-000003",
    item: "1",
    product: "FitDesk Pro",
    offering: "Team",
    gross: inr(1244299),
    discount: inr(0),
    tax: inr(0),
    gatewayFee: inr(0),
    bankCharge: inr(0),
    distributable: inr(1244299),
    companyCut: { bps: 2000, amount: inr(248860) },
    partners: [
      { name: "Priya Nair", bps: 5000, amount: inr(622150) },
      { name: "Arjun Mehta", bps: 3000, amount: inr(373289) },
    ],
    ownershipVersion: "v2 · effective 1 Aug",
  },
  {
    id: "al-4",
    at: "2026-09-22T10:00:00Z",
    order: "CK-ORD-000005",
    item: "1",
    product: "ShopSync",
    offering: "Pro",
    gross: inr(-299800),
    discount: inr(0),
    tax: inr(-53964),
    gatewayFee: inr(0),
    bankCharge: inr(0),
    distributable: inr(-299800),
    companyCut: { bps: 2000, amount: inr(-59960) },
    partners: [
      { name: "Priya Nair", bps: 4000, amount: inr(-119920) },
      { name: "Arjun Mehta", bps: 4000, amount: inr(-119920) },
    ],
    ownershipVersion: "v1 · effective 1 Mar",
    isRefund: true,
  },
];

export const PARTNER_BALANCES: PartnerBalance[] = [
  {
    id: "p-priya",
    name: "Priya Nair",
    role: "CEO · Partner A",
    active: true,
    balanceInr: 6124000,
    perCurrency: [inr(5501850), usd(74500)],
    earnedInr: 18924000,
    paidOutInr: 12800000,
    pendingPayoutApprovals: 0,
    sparkline: [12, 18, 15, 22, 30, 26, 34, 31, 40, 38, 45, 52],
    history: [
      {
        month: "Sep 2026",
        allocations: 2087910,
        refunds: -119920,
        expenses: -480000,
        payouts: 0,
        closing: 6124000,
      },
      {
        month: "Aug 2026",
        allocations: 1840000,
        refunds: 0,
        expenses: -480000,
        payouts: -2000000,
        closing: 4636010,
      },
      {
        month: "Jul 2026",
        allocations: 2210000,
        refunds: -50000,
        expenses: -450000,
        payouts: -2500000,
        closing: 5276010,
      },
    ],
  },
  {
    id: "p-arjun",
    name: "Arjun Mehta",
    role: "CFO · Partner B",
    active: true,
    balanceInr: 1924000,
    perCurrency: [inr(1476800), usd(44700)],
    earnedInr: 15210000,
    paidOutInr: 13286000,
    pendingPayoutApprovals: 0,
    sparkline: [10, 14, 12, 20, 24, 22, 28, 30, 27, 33, 36, 41],
    history: [
      {
        month: "Sep 2026",
        allocations: 1398622,
        refunds: -119920,
        expenses: -320000,
        payouts: -4200000,
        closing: 1924000,
      },
      {
        month: "Aug 2026",
        allocations: 1520000,
        refunds: 0,
        expenses: -320000,
        payouts: 0,
        closing: 5165298,
      },
      {
        month: "Jul 2026",
        allocations: 1710000,
        refunds: -50000,
        expenses: -300000,
        payouts: -1500000,
        closing: 3965298,
      },
    ],
  },
];

export const COMPANY_CARD = {
  companyCutInr: 8240000,
  companyExpensesInr: 1200000,
  netInr: 7040000,
};

export const PAYOUTS: PayoutRow[] = [
  {
    id: "po-1",
    paidOn: "2026-09-23",
    partner: "Arjun Mehta",
    amount: inr(4200000),
    reference: "NEFT N268261234567",
    note: "September payout",
    recordedBy: "Priya Nair",
    approvedBy: "Arjun Mehta",
    approvedAt: "2026-09-23T14:29:00Z",
    status: "applied",
    ledgerSeq: 1088,
  },
  {
    id: "po-2",
    paidOn: "2026-08-15",
    partner: "Priya Nair",
    amount: inr(2000000),
    reference: "NEFT N267901112233",
    recordedBy: "Arjun Mehta",
    approvedBy: "Priya Nair",
    approvedAt: "2026-08-15T11:00:00Z",
    status: "applied",
    ledgerSeq: 1032,
  },
  {
    id: "po-3",
    paidOn: "2026-09-25",
    partner: "Priya Nair",
    amount: inr(3000000),
    reference: "IMPS 6269…",
    note: "Advance for Q3",
    recordedBy: "Arjun Mehta",
    status: "pending",
  },
  {
    id: "po-4",
    paidOn: "2026-07-30",
    partner: "Arjun Mehta",
    amount: inr(6000000),
    reference: "NEFT N266…",
    recordedBy: "Priya Nair",
    approvedBy: "Arjun Mehta",
    approvedAt: "2026-07-30T09:00:00Z",
    status: "rejected",
    rejectionReason: "Exceeded balance at the time; re-recorded as ₹1,500,000.",
  },
];

export const EXPENSES: ExpenseRow[] = [
  {
    id: "ex-31",
    at: "2026-09-21",
    description: "Hosting · Hetzner · September",
    category: "Hosting",
    amount: inr(1200000),
    amountInr: 1200000,
    sharedBySplit: false,
    receipt: "hetzner-sep.pdf",
    recordedBy: "Priya Nair",
    ledgerSeq: 1083,
  },
  {
    id: "ex-30",
    at: "2026-09-18",
    description: "Calendar API licence · FitDesk Pro",
    category: "Licences/tools",
    product: "FitDesk Pro",
    amount: usd(4900),
    amountInr: 409199,
    sharedBySplit: true,
    receipt: "cronofy.pdf",
    recordedBy: "Arjun Mehta",
    ledgerSeq: 1070,
  },
  {
    id: "ex-29",
    at: "2026-09-12",
    description: "Contractor · TradeFlow docs refresh",
    category: "Contractors",
    product: "TradeFlow",
    amount: inr(2500000),
    amountInr: 2500000,
    sharedBySplit: true,
    recordedBy: "Priya Nair",
    ledgerSeq: 1061,
  },
  {
    id: "ex-28",
    at: "2026-09-05",
    description: "Domain renewals",
    category: "Domains",
    amount: inr(340000),
    amountInr: 340000,
    sharedBySplit: false,
    receipt: "namecheap.pdf",
    recordedBy: "Arjun Mehta",
    ledgerSeq: 1050,
  },
  {
    id: "ex-27",
    at: "2026-09-02",
    description: "LinkedIn ads · FitDesk Pro launch",
    category: "Marketing",
    product: "FitDesk Pro",
    amount: inr(1500000),
    amountInr: 1500000,
    sharedBySplit: true,
    recordedBy: "Priya Nair",
    ledgerSeq: 1044,
  },
];

export const ADJUSTMENTS: AdjustmentRow[] = [
  {
    id: "adj-3",
    createdAt: "2026-09-24T09:15:00Z",
    reason:
      "Write off the ₹40 bank shortfall on CK-ORD-000009 as a bank charge instead of leaving it as a receivable.",
    lines: [
      {
        partyType: "bank",
        amount: inr(-4000),
        memo: "Shortfall write-off",
        order: "CK-ORD-000009",
      },
      { partyType: "company", amount: inr(4000), memo: "Balancing line" },
    ],
    requestedBy: "Arjun Mehta",
    status: "pending",
  },
  {
    id: "adj-2",
    createdAt: "2026-08-30T10:00:00Z",
    reason:
      "Hosting expense recorded against ShopSync instead of company; move ₹12,000 back to company-only.",
    lines: [
      {
        partyType: "partner",
        partner: "Priya Nair",
        amount: inr(480000),
        memo: "Reverse expense share",
      },
      {
        partyType: "partner",
        partner: "Arjun Mehta",
        amount: inr(480000),
        memo: "Reverse expense share",
      },
      { partyType: "company", amount: inr(-960000), memo: "Company absorbs hosting" },
    ],
    requestedBy: "Priya Nair",
    approver: "Arjun Mehta",
    decidedAt: "2026-08-30T15:00:00Z",
    status: "applied",
    ledgerSeqs: [1040, 1041, 1042],
  },
  {
    id: "adj-1",
    createdAt: "2026-07-12T10:00:00Z",
    reason: "Received amount mis-typed on CK-ORD-000002 (₹2,990 vs ₹299).",
    lines: [
      {
        partyType: "company",
        amount: inr(-269100),
        memo: "Correct received amount",
        order: "CK-ORD-000002",
      },
    ],
    requestedBy: "Arjun Mehta",
    approver: "Priya Nair",
    decidedAt: "2026-07-12T12:00:00Z",
    status: "rejected",
  },
];

const MONTHS = ["Apr", "May", "Jun", "Jul", "Aug", "Sep"];
export const REPORTS: ReportDefinition[] = [
  {
    key: "revenue_by_period",
    title: "Revenue by period",
    description: "Net sales posted to the ledger per month (INR reporting currency).",
    formula: "Σ sale − Σ discount − Σ refund_sale, grouped by payment date",
    tiles: [
      { label: "Gross", valueInr: 14210000, delta: "+12 % vs last FY" },
      { label: "Net", valueInr: 13480000 },
      { label: "Tax", valueInr: 2426400 },
      { label: "Refunds", valueInr: 299800 },
    ],
    series: MONTHS.map((m, i) => ({
      label: m,
      value: [1800000, 2100000, 1950000, 2600000, 2400000, 3360000][i] as number,
    })),
    columns: ["Month", "Orders", "Gross", "Discounts", "Refunds", "Net"],
    rows: MONTHS.map((m, i) => [
      m,
      [6, 8, 7, 9, 8, 11][i] as number,
      "₹" + ([18, 21, 19.5, 26, 24, 33.6][i] as number) + "L",
      "₹0.3L",
      i === 5 ? "₹3.0L" : "₹0",
      "₹" + ([17.7, 20.7, 19.2, 25.7, 23.7, 30.3][i] as number) + "L",
    ]),
    totals: ["Total", 49, "₹1.42Cr", "₹1.8L", "₹3.0L", "₹1.35Cr"],
  },
  {
    key: "revenue_by_product",
    title: "Revenue by product",
    description: "Net revenue per product with order counts.",
    formula: "Σ sale − Σ refund_sale per product",
    tiles: [
      { label: "Products sold", valueInr: 6 },
      { label: "Net", valueInr: 13480000 },
    ],
    series: [
      { label: "TradeFlow", value: 6200000 },
      { label: "FitDesk Pro", value: 4100000 },
      { label: "ShopSync", value: 1800000 },
      { label: "Brand Kit", value: 380000 },
      { label: "InvoiceKit", value: 0 },
    ],
    columns: ["Product", "Orders", "Net revenue", "Share"],
    rows: [
      ["TradeFlow", 17, "₹62.0L", "46 %"],
      ["FitDesk Pro", 42, "₹41.0L", "30 %"],
      ["ShopSync", 11, "₹18.0L", "13 %"],
      ["Brand Kit Templates", 6, "₹3.8L", "3 %"],
    ],
  },
  {
    key: "revenue_by_partner",
    title: "Revenue by partner",
    description: "Partner allocations net of refund reversals.",
    formula: "Σ partner_allocation − Σ refund_partner_allocation",
    tiles: [
      { label: "Priya Nair", valueInr: 6124000 },
      { label: "Arjun Mehta", valueInr: 5324000 },
      { label: "Company", valueInr: 2696000 },
    ],
    series: [
      { label: "Priya", value: 6124000 },
      { label: "Arjun", value: 5324000 },
      { label: "Company", value: 2696000 },
    ],
    columns: ["Party", "Allocations", "Reversals", "Net"],
    rows: [
      ["Priya Nair", "₹62.4L", "−₹1.2L", "₹61.2L"],
      ["Arjun Mehta", "₹54.4L", "−₹1.2L", "₹53.2L"],
      ["Company", "₹27.6L", "−₹0.6L", "₹27.0L"],
    ],
  },
  {
    key: "tax_collected",
    title: "Tax collected",
    description: "GST collected per month with CGST/SGST vs IGST split.",
    formula: "Σ tax_collected − Σ refund_tax",
    tiles: [
      { label: "Tax collected", valueInr: 2426400 },
      { label: "IGST", valueInr: 1626400 },
      { label: "CGST + SGST", valueInr: 800000 },
    ],
    series: MONTHS.map((m, i) => ({
      label: m,
      value: [324000, 378000, 351000, 468000, 432000, 473400][i] as number,
    })),
    columns: ["Month", "Taxable", "CGST", "SGST", "IGST", "Total"],
    rows: MONTHS.map((m) => [m, "₹18L", "₹0.9L", "₹0.9L", "₹1.4L", "₹3.2L"]),
  },
  {
    key: "refunds",
    title: "Refunds & customer credits",
    description: "Refunds issued (credit notes) and overpayments held as customer credit.",
    formula: "Σ refund_* entries; credits from the customer_credits view",
    tiles: [
      { label: "Refunded", valueInr: 299800 },
      { label: "Credit notes", valueInr: 1 },
      { label: "Open customer credits", valueInr: 12000 },
    ],
    series: MONTHS.map((m, i) => ({ label: m, value: [0, 50000, 0, 0, 0, 299800][i] as number })),
    columns: ["Date", "Order", "Credit note", "Amount", "Reason"],
    rows: [
      ["22 Sep 2026", "CK-ORD-000005", "CN/2026-27/0001", "₹2,998.00", "Chargeback settled"],
      ["14 May 2026", "CK-ORD-000001", "CN/2025-26/0004", "₹500.00", "Duplicate purchase"],
    ],
  },
  {
    key: "outstanding_payouts",
    title: "Outstanding payouts",
    description: "Partner balances not yet paid out.",
    formula: "partner_balances view",
    tiles: [
      { label: "Outstanding", valueInr: 8048000 },
      { label: "Awaiting approval", valueInr: 3000000 },
    ],
    series: [
      { label: "Priya", value: 6124000 },
      { label: "Arjun", value: 1924000 },
    ],
    columns: ["Partner", "Balance", "Pending payout", "After"],
    rows: [
      ["Priya Nair", "₹61,240.00", "₹30,000.00", "₹31,240.00"],
      ["Arjun Mehta", "₹19,240.00", "₹0", "₹19,240.00"],
    ],
  },
  {
    key: "profit_by_product",
    title: "Profit by product",
    description: "Revenue minus expenses recorded against each product.",
    formula: "net revenue − Σ expense per product",
    tiles: [
      { label: "Revenue", valueInr: 13480000 },
      { label: "Expenses", valueInr: 5949199 },
      { label: "Profit", valueInr: 7530801 },
    ],
    series: [
      { label: "TradeFlow", value: 3700000 },
      { label: "FitDesk Pro", value: 2190801 },
      { label: "ShopSync", value: 1800000 },
      { label: "Brand Kit", value: 380000 },
    ],
    columns: ["Product", "Revenue", "Expenses", "Profit", "Margin"],
    rows: [
      ["TradeFlow", "₹62.0L", "₹25.0L", "₹37.0L", "60 %"],
      ["FitDesk Pro", "₹41.0L", "₹19.1L", "₹21.9L", "53 %"],
      ["ShopSync", "₹18.0L", "₹0", "₹18.0L", "100 %"],
      ["Brand Kit Templates", "₹3.8L", "₹0", "₹3.8L", "100 %"],
    ],
  },
];

export const CUSTOMER_CREDITS: CustomerCreditRow[] = [
  { order: "CK-ORD-000009", payment: "pay-9", credit: inr(12000), state: "open" },
  { order: "CK-ORD-000004", payment: "pay-4b", credit: inr(5000), state: "refunded" },
];

export const STATEMENT_PREVIEW: StatementPreview = {
  partner: "Priya Nair",
  period: "01 Sep – 30 Sep 2026",
  opening: 4636010,
  allocations: [
    { order: "CK-ORD-000009", amount: 998360 },
    { order: "CK-ORD-000007", amount: 44955 },
    { order: "CK-ORD-000003", amount: 622150 },
    { order: "CK-ORD-000011 (quote)", amount: 422445 },
  ],
  refunds: -119920,
  expenseShares: -480000,
  payouts: 0,
  closing: 6124000,
};

export const STATEMENT_HISTORY: StatementHistoryRow[] = [
  {
    id: "st-1",
    partner: "Arjun Mehta",
    period: "Aug 2026",
    format: "PDF",
    generatedBy: "Arjun Mehta",
    generatedAt: "2026-09-02T10:00:00Z",
  },
  {
    id: "st-2",
    partner: "Priya Nair",
    period: "Aug 2026",
    format: "CSV",
    generatedBy: "Priya Nair",
    generatedAt: "2026-09-01T09:00:00Z",
  },
];

/* ------------------------------------------------------------------ content */

export const LANDING_CHAPTERS: LandingChapter[] = [
  {
    key: "who",
    title: "We build software that sells itself",
    subtitle: "CodeKraft — software studio",
    body: "A small studio shipping products and custom builds for teams that care about craft.",
    published: true,
    poster: "hero-poster.webp",
    ctaPrimary: { label: "Start a project", target: "inquiry" },
    ctaSecondary: { label: "Explore products", target: "/products" },
  },
  {
    key: "build",
    title: "What we build",
    body: "Custom platforms, integrations and migrations — scoped, shipped, supported.",
    published: true,
  },
  {
    key: "sell",
    title: "What we sell",
    body: "Ready-to-run products with manual, human-verified payments.",
    published: true,
  },
  {
    key: "proof",
    title: "Proof",
    body: "Case studies, testimonials and the numbers behind them.",
    published: true,
  },
  {
    key: "talk",
    title: "Talk to us",
    body: "Tell us about the project; we reply within one business day.",
    published: false,
  },
];

export const SERVICES: ServiceRow[] = [
  {
    id: "s1",
    title: "Custom software",
    slug: "custom-software",
    summary: "Web platforms and internal tools built to spec.",
    icon: "code",
    deliverables: ["Discovery workshop", "Architecture note", "Weekly demos"],
    published: true,
  },
  {
    id: "s2",
    title: "Integrations",
    slug: "integrations",
    summary: "Connect payments, CRMs, ERPs and messaging.",
    icon: "plug",
    deliverables: ["Integration map", "Sandbox tests"],
    published: true,
  },
  {
    id: "s3",
    title: "Migration",
    slug: "migration",
    summary: "Move data and users off legacy systems safely.",
    icon: "move",
    deliverables: ["Migration plan", "Dry run", "Cut-over"],
    published: true,
  },
  {
    id: "s4",
    title: "Implementation",
    slug: "implementation",
    summary: "Roll out our products in your organisation.",
    icon: "rocket",
    deliverables: ["Onboarding", "SSO"],
    published: true,
  },
  {
    id: "s5",
    title: "Design systems",
    slug: "design-systems",
    summary: "Tokens, components and docs for product teams.",
    icon: "palette",
    deliverables: ["Token sheet", "Component library"],
    published: false,
  },
];

export const CASE_STUDIES: CaseStudyRow[] = [
  {
    id: "cs1",
    title: "Cutting checkout drop-off for a textile exporter",
    slug: "global-textiles-portal",
    client: "Global Textiles",
    industry: "Manufacturing",
    tech: ["Next.js", "Postgres", "Razorpay"],
    status: "published",
    publishedAt: "2026-08-12",
    updatedAt: "2026-09-01T10:00:00Z",
  },
  {
    id: "cs2",
    title: "Migrating three stores to a hosted platform",
    slug: "nimbus-shopsync",
    client: "Confidential client",
    industry: "Retail",
    tech: ["ShopSync", "Magento"],
    status: "draft",
    updatedAt: "2026-09-20T10:00:00Z",
  },
  {
    id: "cs3",
    title: "A wellness dashboard for 400 desks",
    slug: "fitdesk-rollout",
    client: "Confidential client",
    industry: "Consulting",
    tech: ["FitDesk Pro", "Slack"],
    status: "published",
    publishedAt: "2026-06-01",
    updatedAt: "2026-06-01T10:00:00Z",
  },
];

export const SITE_TESTIMONIALS: TestimonialItem[] = [
  {
    id: "st1",
    quote:
      "CodeKraft shipped our client portal in nine weeks and it has run without a hiccup since.",
    author: "Ops director",
    company: "Global Textiles",
    context: "site",
    published: true,
  },
  {
    id: "st2",
    quote:
      "The manual payment flow felt safer than any gateway — our finance team loved the invoice trail.",
    author: "Finance lead",
    company: "Nimbus Retail",
    context: "site",
    published: true,
  },
  {
    id: "st3",
    quote: "Fast, honest, and they said no to scope creep before we did.",
    author: "Founder",
    company: "FinOps Labs",
    context: "site",
    published: false,
  },
  ...PRODUCT_EDITOR.testimonials,
];

export const LOGOS: ClientLogo[] = [
  { id: "l1", name: "Global Textiles", url: "https://globaltextiles.example", published: true },
  { id: "l2", name: "Nimbus Retail", published: true, lowContrastOnDark: true },
  { id: "l3", name: "FinOps Labs", url: "https://finops.example", published: true },
  { id: "l4", name: "Okafor Logistics", published: false },
];

export const FAQS: FaqItem[] = [
  {
    id: "fq1",
    question: "How do payments work?",
    answer:
      "Pay by UPI or bank transfer, enter the reference, and we confirm within one business day.",
    scope: "site",
    published: true,
  },
  {
    id: "fq2",
    question: "Can I get a GST invoice?",
    answer: "Yes — add your GSTIN at checkout.",
    scope: "site",
    published: true,
  },
  {
    id: "fq3",
    question: "What happens if I overpay?",
    answer: "The excess is held as customer credit and refunded or applied by an admin.",
    scope: "chatbot",
    published: true,
  },
  {
    id: "fq4",
    question: "Which products include source code?",
    answer: "Download and licence products include source; SaaS products do not.",
    scope: "chatbot",
    published: true,
  },
  ...PRODUCT_EDITOR.faqs,
];

export const LEGAL_PAGES: LegalPage[] = [
  {
    key: "privacy",
    title: "Privacy policy",
    version: 3,
    publishedAt: "2026-09-01",
    hasDraft: true,
    effectiveDate: "2026-09-25",
    body: "## 1. What we collect\nAccount details, orders, payment references and chat transcripts (retained 12 months).\n\n## 2. Analytics\nCookie-free analytics via Umami.\n\n## 3. Your rights\nDelete your account from Settings; personal data is anonymised immediately.",
    checklist: [
      { label: "States AI transcript handling and 12-month retention", done: true },
      { label: "States analytics run without cookies", done: true },
      { label: "No public contact details (inquiry form and dashboard only)", done: false },
    ],
    history: [
      {
        version: 3,
        publishedAt: "2026-09-01",
        by: "Priya Nair",
        summary: "Transcript retention clarified",
      },
      { version: 2, publishedAt: "2026-06-10", by: "Priya Nair", summary: "Cookie-free analytics" },
      { version: 1, publishedAt: "2026-03-01", by: "Arjun Mehta", summary: "Initial" },
    ],
  },
  {
    key: "terms",
    title: "Terms of service",
    version: 4,
    publishedAt: "2026-09-10",
    hasDraft: false,
    effectiveDate: "2026-09-10",
    body: "## 1. Agreement\n…",
    checklist: [
      { label: "Governing law: India", done: true },
      { label: "References current refund policy version", done: true },
    ],
    history: [
      {
        version: 4,
        publishedAt: "2026-09-10",
        by: "Priya Nair",
        summary: "Quote acceptance clause",
      },
    ],
  },
  {
    key: "refunds",
    title: "Refund & cancellation policy",
    version: 2,
    publishedAt: "2026-07-01",
    hasDraft: false,
    effectiveDate: "2026-07-01",
    body: "## Refunds\nRefunds are reviewed by admins…",
    checklist: [
      { label: "States refunds are reviewed by admins", done: true },
      { label: "States gateway payments are non-refundable", done: true },
      { label: "Links to product refundability", done: true },
    ],
    history: [
      {
        version: 2,
        publishedAt: "2026-07-01",
        by: "Arjun Mehta",
        summary: "Subscription cancellation at period end",
      },
    ],
  },
  {
    key: "license",
    title: "Product license terms",
    version: 1,
    publishedAt: "2026-03-01",
    hasDraft: false,
    effectiveDate: "2026-03-01",
    body: "## Licence\n…",
    checklist: [
      { label: "Defines seats / sites", done: true },
      { label: "Update policy per offering", done: false },
    ],
    history: [{ version: 1, publishedAt: "2026-03-01", by: "Priya Nair", summary: "Initial" }],
  },
];

/* ------------------------------------------------------------------- system */

export const SETTINGS: SettingsData = {
  general: {
    siteName: "CodeKraft",
    domain: "codekraft.example (placeholder until launch)",
    legalName: "CodeKraft Technologies LLP",
    address: "3rd Floor, Trade Centre, Pune 411045",
    phones: "+91 20 1234 5678 (invoice only)",
    email: "billing@codekraft.in (invoice only)",
    replyTime: "We reply within one business day.",
    snippets: QUERY_THREAD.snippets,
  },
  currencies: {
    base: "INR",
    locked: true,
    pendingOrders: 4,
    enabled: ["INR", "USD", "EUR"],
    fx: [
      { quote: "USD", rate: "83.51000000", asOf: "2026-09-25T02:00:00Z", source: "frankfurter" },
      {
        quote: "EUR",
        rate: "90.12000000",
        asOf: "2026-09-25T02:00:00Z",
        source: "frankfurter",
        override: "90.00000000",
      },
      {
        quote: "GBP",
        rate: "105.40000000",
        asOf: "2026-09-21T02:00:00Z",
        source: "frankfurter",
        stale: true,
      },
      { quote: "CAD", rate: "61.80000000", asOf: "2026-09-25T02:00:00Z", source: "frankfurter" },
    ],
  },
  tax: { gstin: "27AAPFU0939F1ZV", rateBps: 1800, sellerState: "Maharashtra (27)" },
  payments: {
    upiEnabled: true,
    vpa: "codekraft@icici",
    payeeName: "CodeKraft",
    bankEnabled: true,
    accountName: "CodeKraft Technologies LLP",
    accountNumber: "0012 3456 7890",
    ifsc: "ICIC0000012",
    bankName: "ICICI Bank",
    swift: "ICICINBBXXX",
    instructions: "Use the order number as the transfer remark.",
    affectedOfferings: ["FitDesk Pro · Starter", "FitDesk Pro · Team", "TradeFlow · Single site"],
  },
  theme: { defaultTheme: "dark-cinematic", lightEnabled: false },
  ai: {
    model: "claude-sonnet-4-5",
    platformCap: 2000,
    perUserCap: 40,
    timeoutS: 30,
    maxTokens: 1024,
    menuOnly: false,
    usedToday: 1240,
  },
  notifications: {
    email: true,
    inApp: true,
    whatsapp: false,
    digestEnabled: true,
    digestTime: "08:30 IST",
    sender: "no-reply@codekraft.in",
  },
  flags: [
    {
      key: "phone_otp",
      description: "Phone OTP sign-in",
      enabled: false,
      dependency: "Needs an SMS provider in env",
    },
    {
      key: "whatsapp_channel",
      description: "WhatsApp customer notifications",
      enabled: false,
      dependency: "Cost per message; provider keys",
    },
    { key: "theme_light_editorial", description: "Light editorial theme toggle", enabled: false },
    {
      key: "provider_razorpay",
      description: "Razorpay gateway",
      enabled: false,
      dependency: "V1.1 — configure keys first",
    },
    {
      key: "provider_stripe",
      description: "Stripe gateway",
      enabled: false,
      dependency: "V1.1 — configure keys first",
    },
    { key: "provider_paypal", description: "PayPal gateway", enabled: false, dependency: "V1.1" },
    {
      key: "automated_provisioning",
      description: "Automated SaaS provisioning",
      enabled: false,
      dependency: "V2",
    },
    { key: "three_hero", description: "3D landing hero", enabled: true, envOverride: true },
    { key: "bundles", description: "Product bundles", enabled: false, placeholder: true },
    {
      key: "vendor_marketplace",
      description: "Third-party vendors",
      enabled: false,
      placeholder: true,
    },
  ],
  retention: {
    chatMonths: 12,
    recordYears: 7,
    nextPurgeAt: "2026-09-26T02:00:00Z",
    lastRunAt: "2026-09-25T02:00:00Z",
  },
};

export const AUDIT_ROWS: AuditRow[] = [
  {
    id: "au-1",
    at: "2026-09-25T07:05:00Z",
    actor: { ...ARJUN, kind: "admin" },
    action: "catalog.product.submit_for_approval",
    subjectType: "product",
    subjectId: "prod-3",
    subjectHref: href("/products"),
    summary: "status draft → pending_approval",
    ip: "49.36.xx.12",
    requestId: "req_8f21a",
    before: { status: "draft", publish_at: null },
    after: { status: "pending_approval", publish_at: "2026-10-01T03:30:00Z" },
    userAgent: "Chrome 130 · macOS",
    approvalId: "apr-1",
  },
  {
    id: "au-2",
    at: "2026-09-24T09:00:00Z",
    actor: { ...PRIYA, kind: "admin" },
    action: "settings.update",
    subjectType: "site_settings",
    subjectId: "ai",
    subjectHref: href("/settings"),
    summary: "platform_daily_cap 1500 → 2000",
    ip: "103.21.xx.4",
    requestId: "req_7c10b",
    before: { platform_daily_cap: 1500, per_user_daily_cap: 40 },
    after: { platform_daily_cap: 2000, per_user_daily_cap: 40 },
    userAgent: "Safari 18 · macOS",
  },
  {
    id: "au-3",
    at: "2026-09-23T14:30:00Z",
    actor: { id: "system", name: "System", kind: "system" },
    action: "finance.payout.apply",
    subjectType: "payout",
    subjectId: "po-1",
    subjectHref: href("/finance/partners"),
    summary: "ledger seq 1088 posted · ₹42,000.00 to Arjun Mehta",
    ip: "—",
    requestId: "job_payout_apply",
    approvalId: "apr-5",
  },
  {
    id: "au-4",
    at: "2026-09-20T15:02:00Z",
    actor: { ...PRIYA, kind: "admin" },
    action: "payments.confirm",
    subjectType: "order",
    subjectId: "o-9",
    subjectHref: href("/orders"),
    summary: "payment submitted → confirmed · received ₹29,498.42 · shortfall ₹40.00",
    ip: "103.21.xx.4",
    requestId: "req_5a9e2",
    before: { status: "submitted", received_minor: null },
    after: {
      status: "confirmed",
      received_minor: 2949842,
      bank_shortfall_minor: 4000,
      admin_reference: "NEFT N268209876",
    },
    userAgent: "Safari 18 · macOS",
  },
  {
    id: "au-5",
    at: "2026-09-19T08:20:00Z",
    actor: { id: "cust-2", name: "Meera Shah", kind: "customer" },
    action: "auth.login",
    subjectType: "user",
    subjectId: "cust-2",
    subjectHref: href("/customers"),
    summary: "email + password",
    ip: "27.7.xx.90",
    requestId: "req_3b77f",
    userAgent: "Chrome 130 · Android",
  },
  {
    id: "au-6",
    at: "2026-09-12T11:00:00Z",
    actor: { ...ARJUN, kind: "admin" },
    action: "users.customer.suspend",
    subjectType: "user",
    subjectId: "cust-5",
    subjectHref: href("/customers"),
    summary: "status active → suspended · reason: chargeback",
    ip: "49.36.xx.12",
    requestId: "req_2f0aa",
    before: { status: "active" },
    after: { status: "suspended", suspension_reason: "Chargeback on CK-ORD-000005" },
  },
  {
    id: "au-7",
    at: "2026-09-10T16:00:00Z",
    actor: { ...ARJUN, kind: "admin" },
    action: "approvals.reject",
    subjectType: "approval_request",
    subjectId: "apr-7",
    subjectHref: href("/approvals"),
    summary: "admin.user_change rejected",
    ip: "49.36.xx.12",
    requestId: "req_1e9c1",
    approvalId: "apr-7",
  },
  {
    id: "au-8",
    at: "2026-09-08T09:00:00Z",
    actor: { ...PRIYA, kind: "admin" },
    action: "users.partner.bank_details.reveal",
    subjectType: "partner",
    subjectId: "p-arjun",
    subjectHref: href("/admin-users"),
    summary: "bank details revealed",
    ip: "103.21.xx.4",
    requestId: "req_0d4b3",
    before: { account_number: "•••• (redacted)" },
    after: { account_number: "•••• (redacted)" },
  },
];

export const ADMIN_USERS: AdminUserRow[] = [
  {
    id: "u-priya",
    name: "Priya Nair",
    email: "priya@codekraft.in",
    role: "super_admin",
    partner: { displayName: "Priya Nair", activeShares: 4 },
    totp: true,
    lastSignInAt: "2026-09-25T06:02:00Z",
    status: "active",
  },
  {
    id: "u-arjun",
    name: "Arjun Mehta",
    email: "arjun@codekraft.in",
    role: "super_admin",
    partner: { displayName: "Arjun Mehta", activeShares: 4 },
    totp: true,
    lastSignInAt: "2026-09-25T07:00:00Z",
    status: "active",
  },
  {
    id: "u-sam",
    name: "Sam Rao",
    email: "sam@codekraft.in",
    role: "admin",
    totp: false,
    status: "invited",
    pendingApprovalId: "apr-7",
  },
];

/* ---------------------------------------------------------------- dashboard */

export const DASHBOARD: DashboardData = {
  range: "30d",
  revenueByPeriod: [
    { label: "W1", value: 520000 },
    { label: "W2", value: 810000 },
    { label: "W3", value: 640000 },
    { label: "W4", value: 1390000 },
  ],
  revenueByProduct: [
    { label: "TradeFlow", value: 2499900 },
    { label: "FitDesk Pro", value: 1244199 },
    { label: "ShopSync", value: 0 },
    { label: "Brand Kit", value: 89700 },
  ],
  revenueByPartner: [
    { label: "Priya", value: 1665465 },
    { label: "Arjun", value: 1398622 },
    { label: "Company", value: 766022 },
  ],
  myShare: {
    valueInr: 1665465,
    delta: "+18 % vs previous 30 days",
    sparkline: [4, 6, 5, 9, 7, 11, 10, 14],
  },
  outstandingPayouts: {
    totalInr: 8048000,
    items: [
      {
        label: "Priya Nair",
        meta: "₹61,240.00 · payout awaiting approval",
        href: href("/finance/partners"),
        tone: "warning",
      },
      { label: "Arjun Mehta", meta: "₹19,240.00", href: href("/finance/partners") },
    ],
  },
  expensesVsProfit: [
    { label: "Jul", expenses: 750000, profit: 1460000 },
    { label: "Aug", expenses: 800000, profit: 1040000 },
    { label: "Sep", expenses: 1949199, profit: 1410801 },
  ],
  paymentsAwaiting: [
    {
      label: "CK-ORD-000012 · ₹11,798.82",
      meta: "UPI · reference submitted 38 min ago",
      href: href("/orders"),
      tone: "warning",
    },
    {
      label: "CK-ORD-000014 · ₹29,498.82",
      meta: "Bank · reference submitted 2 d ago",
      href: href("/orders"),
      tone: "danger",
    },
    {
      label: "CK-ORD-000013 · ₹299.00",
      meta: "UPI · no reference · expires in 9 h",
      href: href("/orders"),
      tone: "warning",
    },
  ],
  publishApprovals: [
    {
      label: "MIS Portal",
      meta: "Requested by Arjun · 2 h ago",
      href: href("/approvals"),
      tone: "info",
    },
  ],
  splitApprovals: [
    {
      label: "CK-ORD-000015 · Global Textiles",
      meta: "₹4,00,000.00 · 2 lines",
      href: href("/approvals"),
      tone: "info",
    },
  ],
  serviceChecklists: [
    {
      label: "MIS Portal · Global Textiles",
      meta: "3 of 6 steps",
      href: href("/orders"),
      progress: 50,
    },
    {
      label: "FitDesk Pro rollout · Acme",
      meta: "1 of 4 steps",
      href: href("/orders"),
      progress: 25,
    },
  ],
  revocationTasks: [
    {
      label: "ShopSync · Nimbus Retail",
      meta: "Revoke external · 3 d old",
      href: href("/entitlements"),
      tone: "danger",
    },
  ],
  newLeads: {
    count: 4,
    delta: "+2 vs previous 7 days",
    items: [
      { label: "Acme Ltd", meta: "Product CTA · FitDesk Pro", href: href("/leads") },
      { label: "Desai & Co", meta: "Inquiry form · Integrations", href: href("/leads") },
    ],
  },
  funnel: [
    { label: "New", value: 2 },
    { label: "Contacted", value: 2 },
    { label: "Qualified", value: 1 },
    { label: "Proposal", value: 1 },
    { label: "Won", value: 1 },
  ],
  overdueFollowUps: [
    {
      label: "Nimbus Retail · Kavya R.",
      meta: "Overdue by 3 days · Arjun",
      href: href("/leads"),
      tone: "danger",
    },
    {
      label: "Rohit Verma",
      meta: "Overdue by 1 hour · Priya",
      href: href("/leads"),
      tone: "danger",
    },
  ],
  conversionRate: { value: 0.18, delta: "+3 pts vs previous 30 days" },
  openQueries: [
    {
      label: "Download cap reached — can you reset?",
      meta: "Meera Shah · 15 h ago",
      href: href("/queries"),
      tone: "warning",
    },
    {
      label: "Refund request · duplicate Starter",
      meta: "Meera Shah · awaiting approval",
      href: href("/queries"),
    },
    {
      label: "Does TradeFlow support multi-currency?",
      meta: "Visitor · 2 d ago",
      href: href("/queries"),
    },
  ],
  visits: {
    total: 12840,
    delta: "+9 % vs previous 30 days",
    top: [
      { product: "FitDesk Pro", visits: 4210 },
      { product: "TradeFlow", visits: 3180 },
      { product: "ShopSync", visits: 1420 },
    ],
  },
  chatbotUsage: { platform: 1240, platformCap: 2000, usersAtCap: 3, perUserCap: 40 },
  catalogStatus: [
    { status: "draft", count: 1 },
    { status: "pending_approval", count: 1 },
    { status: "scheduled", count: 1 },
    { status: "published", count: 3 },
    { status: "unpublished", count: 1 },
    { status: "archived", count: 1 },
  ],
  newCustomers: { count: 5, delta: "+1 vs previous 30 days", sparkline: [1, 0, 2, 1, 0, 1, 0, 0] },
  systemHealth: [
    { label: "Database", ok: true, detail: "12 ms" },
    { label: "Email (Resend)", ok: true, detail: "queue 0" },
    { label: "Anthropic API", ok: true, detail: "p95 1.9 s" },
    { label: "Cron: orders.expire", ok: false, detail: "failed 02:00" },
  ],
};

export const CUSTOMER_DETAIL: CustomerDetailData = {
  customer: CUSTOMERS[0] as CustomerRow,
  phone: "+91 98xxx 11223",
  stats: { lifetimeSpendInr: 1297764, orders: 3, activeEntitlements: 2, openQueries: 1 },
  orders: ORDERS.filter((o) => o.customer.id === "cust-1"),
  entitlements: ENTITLEMENTS.filter((e) => e.customer.id === "cust-1"),
  queries: QUERIES.filter((q) => q.customer?.id === "cust-1"),
  activity: [
    {
      at: "2026-09-25T08:52:00Z",
      actor: "Ravi Kumar",
      text: "Submitted payment reference for CK-ORD-000012",
    },
    { at: "2026-09-24T14:02:00Z", actor: "Ravi Kumar", text: "Placed order CK-ORD-000012" },
    { at: "2026-09-24T13:55:00Z", actor: "Ravi Kumar", text: "Signed in (email + password)" },
    { at: "2026-09-18T09:00:00Z", actor: "Ravi Kumar", text: "Downloaded OldCRM export (4/5)" },
  ],
  chatUsage: { today: 22, cap: 40 },
  notes:
    "Prefers UPI. Asked about a 40-seat rollout — see lead Acme Ltd. Wants invoices addressed to Kumar Consulting LLP.",
  notesHistory: [
    { at: "2026-09-24T15:00:00Z", by: "Priya Nair" },
    { at: "2026-06-02T10:00:00Z", by: "Arjun Mehta" },
  ],
  billing: {
    name: "Kumar Consulting LLP",
    address: "14 MG Road, Pune 411001",
    country: "IN",
    gstin: "27AAPFU0939F1ZV",
    lastUsedAt: "2026-09-24T14:02:00Z",
  },
  preferences: { currency: "INR", theme: "Site default", emailPrefs: "Order + product updates" },
  flags: { chargeback: false },
  offeringOptions: OFFERING_OPTIONS,
};
